#!/bin/bash

# source this if needed when building on OSX if there are linker errors.
# dylib files in extra-lib-dirs  don't get forwarded to ghc
# in some versions of OSX. See https://github.com/commercialhaskell/stack/issues/1826

case "$(uname)" in
  "Darwin")
    DYLD_LIBRARY_PATH=$(pwd)/vendor/build/
    export DYLD_LIBRARY_PATH
    ;;
  "Linux"|"FreeBSD")
    LD_LIBRARY_PATH=$(pwd)/vendor/build/
    export LD_LIBRARY_PATH
    ;;
  *)
    echo "OS doesn't have known environment variable hacks to set"
    ;;
esac

