resolver: lts-17.4

compiler: ghc-9.0.1

packages:
- codegen
- libtorch-ffi
- libtorch-ffi-helper
- hasktorch
- examples
- examples/model-serving
- experimental/bounding-box
- experimental/dataloader-cifar10
- experimental/gradually-typed
- experimental/untyped-nlp

extra-include-dirs:
- deps/libtorch/include/torch/csrc/api/include
- deps/libtorch/include

extra-lib-dirs:
- deps/libtorch/lib
- deps/mklml/lib
- deps/libtokenizers/lib

extra-deps:
- datasets-0.4.0@sha256:9bfd5b54c6c5e1e72384a890cf29bf85a02007e0a31c98753f7d225be3c7fa6a,4929
- pipes-text-0.0.2.5@sha256:16cfd1927817a1c757b15c37ad95c67e819c28b1c4a6ce9757ab15276ec36ac7,3326
- streaming-cassava-0.1.0.1@sha256:2d1dfeb09af62009e88311fe92f44d06dafb5cdd38879b437ea6adb3bc40acfe,1739
- streaming-bytestring-0.1.7@sha256:5b53960c1c5f8352d46a4f1a604d04340a08dcf7ff27ca3ed31253e02c01fd03,2968
- stm-2.5.0.0@sha256:c238075f9f0711cd6a78eab6001b3e218cdaa745d6377bf83cc21e58ceec2ea1,2100
- require-0.4.10@sha256:41b096daaca0d6be49239add1149af9f34c84640d09a7ffa9b45c55f089b5dac,3759
- git: https://github.com/mcwitt/tintin
  commit: cad1ab21e53a3c734e09143def4fe862ded9e67a
- git: https://github.com/hasktorch/tokenizers
  commit: e4208275b6e7d5e265d454819eec5ec626d4077b
  subdirs:
  - bindings/haskell/tokenizers-haskell

allow-newer: true

nix:
  shell-file: nix/stack-shell.nix

# ghc-options:
#   libtorch-ffi: -j +RTS -A128m -n2m -RTS
#   hasktorch: -j +RTS -A128m -n2m -RTS
