resolver: lts-15.5

packages:
- codegen
- libtorch-ffi
- libtorch-ffi-helper
- hasktorch
- examples
- experimental

extra-include-dirs:
  - deps/libtorch/include/torch/csrc/api/include
  - deps/libtorch/include

extra-lib-dirs:
  - deps/libtorch/lib
  - deps/mklml/lib

# see https://github.com/commercialhaskell/stack/issues/4073
# with-gcc: /usr/local/bin/gcc-7

extra-deps:
# libtorch-ffi
- inline-c-cpp-0.4.0.0
# hasktorch
- ghc-typelits-natnormalise-0.7
- ghc-typelits-knownnat-0.7
- ghc-typelits-extra-0.3.2
# examples/typed-transformer
- git: git://github.com/hasktorch/pipes-text.git
  commit: 3dd3d9519306ea06f0c15ad71bdf57e1dfd0b747
# experimental/dataloader-cifar10
- datasets-0.4.0@sha256:9bfd5b54c6c5e1e72384a890cf29bf85a02007e0a31c98753f7d225be3c7fa6a,4929
- streaming-attoparsec-1.0.0.1@sha256:fe9b878072423d3f075534fe8af24722d9ded1a1129e9a6ed5b71c4a29681b39,1146
- streaming-cassava-0.1.0.1@sha256:2d1dfeb09af62009e88311fe92f44d06dafb5cdd38879b437ea6adb3bc40acfe,1739


nix:
  packages: [zlib.dev, zlib.out]
