name: hasktorch-core
version: '0.1.0.0'
synopsis: Torch for tensors and neural networks in Haskell
description: core tensor abstractions wrapping raw TH bindings
category: Tensors, Machine Learning
author: Austin Huang
license: BSD3
github: austinvhuang/hasktorch

# ghc-options: -Wincomplete-patterns # -fllvm -Wall

# core uses unsafePerformIO to wrap FFI, follow recommendations here:
# https://hackage.haskell.org/package/base-4.10.1.0/docs/src/GHC.IO.Unsafe.html
# in using -fnocase -fno-full-laziness
ghc-options: -fno-cse -fno-full-laziness

dependencies:
- base >=4.7 && <5
- deepseq >= 1.3.0.0
- hasktorch-raw
- managed >=1.0.0 && < 1.1
- microlens >=0.4.8.1
- safe-exceptions >= 0.1.0.0
- singletons >=2.2
- text >=1.2.2.2
- typelits-witnesses >=0.2.3.0
- dimensions >= 0.3.2.0

library:
  source-dirs:
  - src
  - src/generic

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
      - tests/generic
    dependencies:
      - QuickCheck
      - hspec
      - hasktorch-core
