module Torch.Class.NN where

import Foreign.C.Types
import Torch.Class.Types

class NN t where
  abs_updateOutput             :: t -> t -> IO ()
  abs_updateGradInput          :: t -> t -> t -> IO ()
  absCriterion_updateOutput    :: t -> t -> t -> Bool -> Bool -> IO ()
  absCriterion_updateGradInput :: t -> t -> t -> t -> Bool -> Bool -> IO ()
  bCECriterion_updateOutput    :: t -> t -> t -> Bool -> t -> Bool -> IO ()
  bCECriterion_updateGradInput :: t -> t -> t -> t -> Bool -> t -> Bool -> IO ()
  eLU_updateOutput             :: t -> t -> Double -> Double -> Bool -> IO ()
  eLU_updateGradInput          :: t -> t -> t -> Double -> Double -> IO ()
  distKLDivCriterion_updateOutput    :: t -> t -> t -> Bool -> Bool -> IO ()
  distKLDivCriterion_updateGradInput :: t -> t -> t -> t -> Bool -> Bool -> IO ()
  gatedLinear_updateOutput     :: t -> t -> Int -> IO ()
  gatedLinear_updateGradInput  :: t -> t -> t -> Int -> IO ()
  hardTanh_updateOutput        :: t -> t -> Double -> Double -> Bool -> IO ()
  hardTanh_updateGradInput     :: t -> t -> t -> Double -> Double -> Bool -> IO ()
  im2Col_updateOutput          :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  im2Col_updateGradInput       :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  col2Im_updateOutput          :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  l1Cost_updateOutput          :: t -> t -> IO ()
  l1Cost_updateGradInput       :: t -> t -> t -> IO ()
  leakyReLU_updateOutput       :: t -> t -> Double -> Bool -> IO ()
  leakyReLU_updateGradInput    :: t -> t -> t -> Double -> Bool -> IO ()
  gRUFused_updateOutput        :: t -> t -> t -> t -> t -> t -> t -> IO ()
  gRUFused_updateGradInput     :: t -> t -> t -> t -> t -> IO ()
  lSTMFused_updateOutput       :: t -> t -> t -> t -> t -> t -> t -> IO ()
  lSTMFused_updateGradInput    :: t -> t -> t -> t -> t -> t -> t -> IO ()
  logSigmoid_updateOutput      :: t -> t -> t -> IO ()
  logSigmoid_updateGradInput   :: t -> t -> t -> t -> IO ()
  logSoftMax_updateOutput      :: t -> t -> DimReal t -> IO ()
  logSoftMax_updateGradInput   :: t -> t -> t -> t -> DimReal t -> IO ()
  marginCriterion_updateOutput        :: t -> t -> t -> Bool -> Double -> IO ()
  marginCriterion_updateGradInput     :: t -> t -> t -> Bool -> Double -> IO ()
  softMarginCriterion_updateOutput    :: t -> t -> t -> Bool -> Bool -> IO ()
  softMarginCriterion_updateGradInput :: t -> t -> t -> t -> Bool -> Bool -> IO ()
  mSECriterion_updateOutput    :: t -> t -> t -> Bool -> Bool -> IO ()
  mSECriterion_updateGradInput :: t -> t -> t -> t -> Bool -> Bool -> IO ()
  pReLU_updateOutput       :: t -> t -> t -> IO ()
  pReLU_updateGradInput    :: t -> t -> t -> t -> IO ()
  pReLU_accGradParameters  :: t -> t -> t -> t -> t -> Double -> IO ()
  rReLU_updateOutput       :: t -> t -> t -> Double -> Double -> Bool -> Bool -> Generator t -> IO ()
  rReLU_updateGradInput    :: t -> t -> t -> t -> Double -> Double -> Bool -> Bool -> IO ()
  sigmoid_updateOutput     :: t -> t -> IO ()
  sigmoid_updateGradInput  :: t -> t -> t -> IO ()
  smoothL1Criterion_updateOutput    :: t -> t -> t -> Bool -> Bool -> IO ()
  smoothL1Criterion_updateGradInput :: t -> t -> t -> t -> Bool -> Bool -> IO ()
  softMax_updateOutput       :: t -> t -> DimReal t -> IO ()
  softMax_updateGradInput    :: t -> t -> t -> t -> DimReal t -> IO ()
  softPlus_updateOutput      :: t -> t -> Double -> Double -> IO ()
  softPlus_updateGradInput   :: t -> t -> t -> t -> Double -> Double -> IO ()
  softShrink_updateOutput    :: t -> t -> Double -> IO ()
  softShrink_updateGradInput :: t -> t -> t -> Double -> IO ()
  sparseLinear_updateOutput             :: t -> t -> t -> t -> IO ()
  sparseLinear_accGradParameters        :: t -> t -> t -> t -> t -> t -> Double -> Double -> IO ()
  sparseLinear_zeroGradParameters       :: t -> t -> t -> IO ()
  sparseLinear_updateParameters         :: t -> t -> t -> t -> t -> Double -> IO ()
  sparseLinear_legacyUpdateOutput       :: t -> t -> t -> t -> IO ()
  sparseLinear_legacyAccGradParameters  :: t -> t -> t -> t -> t -> t -> Double -> Double -> IO ()
  sqrt_updateOutput         :: t -> t -> Double -> IO ()
  sqrt_updateGradInput      :: t -> t -> t -> t -> IO ()
  square_updateOutput       :: t -> t -> IO ()
  square_updateGradInput    :: t -> t -> t -> IO ()
  tanh_updateOutput         :: t -> t -> IO ()
  tanh_updateGradInput      :: t -> t -> t -> IO ()
  threshold_updateOutput    :: t -> t -> Double -> Double -> Bool -> IO ()
  threshold_updateGradInput :: t -> t -> t -> Double -> Double -> Bool -> IO ()
  temporalConvolution_updateOutput                   :: t -> t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  temporalConvolution_updateGradInput                :: t -> t -> t -> t -> Int -> Int -> IO ()
  temporalConvolution_accGradParameters              :: t -> t -> t -> t -> Int -> Int -> Double -> IO ()
  temporalRowConvolution_updateOutput                :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Bool -> IO ()
  temporalRowConvolution_updateGradInput             :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Bool -> IO ()
  temporalRowConvolution_accGradParameters           :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Bool -> Double -> IO ()
  temporalUpSamplingNearest_updateOutput             :: t -> t -> Int -> IO ()
  temporalUpSamplingNearest_updateGradInput          :: t -> t -> t -> Int -> IO ()
  temporalUpSamplingLinear_updateOutput              :: t -> t -> Int -> IO ()
  temporalUpSamplingLinear_updateGradInput           :: t -> t -> Int -> Int -> Int -> Int -> IO ()
  batchNormalization_updateOutput                    :: t -> t -> t -> t -> t -> t -> t -> t -> Bool -> Double -> Double -> IO ()
  batchNormalization_backward                        :: t -> t -> t -> t -> t -> t -> t -> t -> t -> t -> Bool -> Double -> Double -> IO ()
  spatialConvolutionMM_updateOutput                  :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialConvolutionMM_updateGradInput               :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialConvolutionMM_accGradParameters             :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialConvolutionLocal_updateOutput               :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> IO ()
  spatialConvolutionLocal_updateGradInput            :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> IO ()
  spatialConvolutionLocal_accGradParameters          :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> Double -> IO ()
  spatialAdaptiveAveragePooling_updateOutput         :: t -> t -> Int -> Int -> IO ()
  spatialAdaptiveAveragePooling_updateGradInput      :: t -> t -> t -> IO ()
  spatialAveragePooling_updateOutput                 :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  spatialAveragePooling_updateGradInput              :: t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  spatialFullConvolution_updateOutput                :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolution_updateGradInput             :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolution_accGradParameters           :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialDilatedConvolution_updateOutput             :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialDilatedConvolution_updateGradInput          :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialDilatedConvolution_accGradParameters        :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialFullDilatedConvolution_updateOutput         :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullDilatedConvolution_updateGradInput      :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullDilatedConvolution_accGradParameters    :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialSubSampling_updateOutput                    :: t -> t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialSubSampling_updateGradInput                 :: t -> t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialSubSampling_accGradParameters               :: t -> t -> t -> t -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialUpSamplingNearest_updateOutput              :: t -> t -> Int -> IO ()
  spatialUpSamplingNearest_updateGradInput           :: t -> t -> t -> Int -> IO ()
  spatialUpSamplingBilinear_updateOutput             :: t -> t -> Int -> Int -> IO ()
  spatialUpSamplingBilinear_updateGradInput          :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialGridSamplerBilinear_updateOutput            :: t -> t -> t -> Int -> IO ()
  spatialGridSamplerBilinear_updateGradInput         :: t -> t -> t -> t -> t -> Int -> IO ()
  volumetricGridSamplerBilinear_updateOutput         :: t -> t -> t -> Int -> IO ()
  volumetricGridSamplerBilinear_updateGradInput      :: t -> t -> t -> t -> t -> Int -> IO ()
  volumetricAveragePooling_updateOutput              :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  volumetricAveragePooling_updateGradInput           :: t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  volumetricConvolution_updateOutput                 :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolution_updateGradInput              :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolution_accGradParameters            :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricFullConvolution_updateOutput             :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullConvolution_updateGradInput          :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullConvolution_accGradParameters        :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricDilatedConvolution_updateOutput          :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricDilatedConvolution_updateGradInput       :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricDilatedConvolution_accGradParameters     :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricFullDilatedConvolution_updateOutput      :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullDilatedConvolution_updateGradInput   :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullDilatedConvolution_accGradParameters :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricAdaptiveAveragePooling_updateOutput      :: t -> t -> Int -> Int -> Int -> IO ()
  volumetricAdaptiveAveragePooling_updateGradInput   :: t -> t -> t -> IO ()
  spatialReflectionPadding_updateOutput              :: t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialReflectionPadding_updateGradInput           :: t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialReplicationPadding_updateOutput             :: t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialReplicationPadding_updateGradInput          :: t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  featureLPPooling_updateOutput                      :: t -> t -> Double -> Int -> Int -> Bool -> IO ()
  featureLPPooling_updateGradInput                   :: t -> t -> t -> t -> Double -> Int -> Int -> Bool -> IO ()
  volumetricReplicationPadding_updateOutput          :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricReplicationPadding_updateGradInput       :: t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricUpSamplingNearest_updateOutput           :: t -> t -> Int -> IO ()
  volumetricUpSamplingNearest_updateGradInput        :: t -> t -> t -> Int -> IO ()
  volumetricUpSamplingTrilinear_updateOutput         :: t -> t -> Int -> Int -> Int -> IO ()
  volumetricUpSamplingTrilinear_updateGradInput      :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  temporalReflectionPadding_updateOutput             :: t -> t -> Int -> Int -> IO ()
  temporalReflectionPadding_updateGradInput          :: t -> t -> t -> Int -> Int -> IO ()
  temporalReplicationPadding_updateOutput            :: t -> t -> Int -> Int -> IO ()
  temporalReplicationPadding_updateGradInput         :: t -> t -> t -> Int -> Int -> IO ()

class CPUNN t where
  unfolded_acc  :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  unfolded_copy :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_updateOutput :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_updateGradInput :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_accGradParameters :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  temporalSubSampling_updateOutput :: t -> t -> t -> t -> Int -> Int -> Int -> IO ()
  temporalSubSampling_updateGradInput :: t -> t -> t -> t -> Int -> Int -> IO ()
  temporalSubSampling_accGradParameters :: t -> t -> t -> t -> Int -> Int -> Double -> IO ()
  spatialFullConvolutionMap_updateOutput :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolutionMap_updateGradInput :: t -> t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolutionMap_accGradParameters :: t -> t -> t -> t -> t -> Int -> Int -> Int -> Int -> Double -> IO ()
  hardShrink_updateOutput      :: t -> t -> Double -> IO ()
  hardShrink_updateGradInput   :: t -> t -> t -> Double -> IO ()
  col2Im_updateGradInput       :: t -> t -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  linear_updateOutput      :: t -> t -> t -> t -> t -> IO ()
  linear_updateGradInput   :: t -> t -> t -> t -> IO ()
  linear_accGradParameters :: t -> t -> t -> t -> t -> t -> t -> t -> Double -> IO ()
  sparseLinear_legacyZeroGradParameters :: t -> t -> t -> IO ()
  sparseLinear_legacyUpdateParameters   :: t -> t -> t -> t -> t -> Double -> IO ()
