{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE TypeSynonymInstances #-}
module Torch.Indef.Tensor.Static.Math.Floating where

import Torch.Signature.Types (Tensor)
import Torch.Class.Tensor.Static
import Torch.Indef.Tensor.Static
import Torch.Indef.Tensor.Dynamic.Math.Floating ()
import qualified Torch.Class.Tensor.Math as Class

instance Class.TensorMathFloating (Tensor d) where
  cinv_ t0 t1 = Class.cinv_ (asDynamic t0) (asDynamic t1)
  sigmoid_ t0 t1 = Class.sigmoid_ (asDynamic t0) (asDynamic t1)
  log_ t0 t1 = Class.log_ (asDynamic t0) (asDynamic t1)
  lgamma_ t0 t1 = Class.lgamma_ (asDynamic t0) (asDynamic t1)
  log1p_ t0 t1 = Class.log1p_ (asDynamic t0) (asDynamic t1)
  exp_ t0 t1 = Class.exp_ (asDynamic t0) (asDynamic t1)
  cos_ t0 t1 = Class.cos_ (asDynamic t0) (asDynamic t1)
  acos_ t0 t1 = Class.acos_ (asDynamic t0) (asDynamic t1)
  cosh_ t0 t1 = Class.cosh_ (asDynamic t0) (asDynamic t1)
  sin_ t0 t1 = Class.sin_ (asDynamic t0) (asDynamic t1)
  asin_ t0 t1 = Class.asin_ (asDynamic t0) (asDynamic t1)
  sinh_ t0 t1 = Class.sinh_ (asDynamic t0) (asDynamic t1)
  tan_ t0 t1 = Class.tan_ (asDynamic t0) (asDynamic t1)
  atan_ t0 t1 = Class.atan_ (asDynamic t0) (asDynamic t1)
  atan2_ t0 t1 t2 = Class.atan2_ (asDynamic t0) (asDynamic t1) (asDynamic t2)
  tanh_ t0 t1 = Class.tanh_ (asDynamic t0) (asDynamic t1)
  erf_ t0 t1 = Class.erf_ (asDynamic t0) (asDynamic t1)
  erfinv_ t0 t1 = Class.erfinv_ (asDynamic t0) (asDynamic t1)
  pow_ t0 t1 = Class.pow_ (asDynamic t0) (asDynamic t1)
  tpow_ t0 v t1 = Class.tpow_ (asDynamic t0) v (asDynamic t1)
  sqrt_ t0 t1 = Class.sqrt_ (asDynamic t0) (asDynamic t1)
  rsqrt_ t0 t1 = Class.rsqrt_ (asDynamic t0) (asDynamic t1)
  ceil_ t0 t1 = Class.ceil_ (asDynamic t0) (asDynamic t1)
  floor_ t0 t1 = Class.floor_ (asDynamic t0) (asDynamic t1)
  round_ t0 t1 = Class.round_ (asDynamic t0) (asDynamic t1)
  trunc_ t0 t1 = Class.trunc_ (asDynamic t0) (asDynamic t1)
  frac_ t0 t1 = Class.frac_ (asDynamic t0) (asDynamic t1)
  lerp_ t0 t1 t2 = Class.lerp_ (asDynamic t0) (asDynamic t1) (asDynamic t2)
  mean_ t0 t1 = Class.mean_ (asDynamic t0) (asDynamic t1)
  std_ t0 t1 = Class.std_ (asDynamic t0) (asDynamic t1)
  var_ t0 t1 = Class.var_ (asDynamic t0) (asDynamic t1)
  norm_ t0 t1 = Class.norm_ (asDynamic t0) (asDynamic t1)
  renorm_ t0 t1 = Class.renorm_ (asDynamic t0) (asDynamic t1)
  dist t0 t1 = Class.dist (asDynamic t0) (asDynamic t1)
  histc_ t0 t1 = Class.histc_ (asDynamic t0) (asDynamic t1)
  bhistc_ t0 t1 = Class.bhistc_ (asDynamic t0) (asDynamic t1)
  meanall t0 = Class.meanall (asDynamic t0)
  varall t0 = Class.varall (asDynamic t0)
  stdall t0 = Class.stdall (asDynamic t0)
  normall t0 = Class.normall (asDynamic t0)
  linspace_ t0 = Class.linspace_ (asDynamic t0)
  logspace_ t0 = Class.logspace_ (dynamic t0)
  rand_ t0 = Class.rand_ (asDynamic t0)
  randn_ t0 = Class.randn_ (asDynamic t0)

