{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE TypeSynonymInstances #-}
module Torch.Indef.Tensor.Static.Math.Floating where

import Torch.Sig.Types (Tensor)
import Torch.Class.Tensor.Static
import Torch.Indef.Tensor.Static
import Torch.Indef.Tensor.Dynamic.Math.Floating ()
import qualified Torch.Class.Tensor.Math as Class

instance Class.TensorMathFloating (Tensor d) where
  cinv_ t0 t1 = Class.cinv_ (dynamicamic t0) (dynamicamic t1)
  sigmoid_ t0 t1 = Class.sigmoid_ (dynamicamic t0) (dynamicamic t1)
  log_ t0 t1 = Class.log_ (dynamicamic t0) (dynamicamic t1)
  lgamma_ t0 t1 = Class.lgamma_ (dynamicamic t0) (dynamicamic t1)
  log1p_ t0 t1 = Class.log1p_ (dynamicamic t0) (dynamicamic t1)
  exp_ t0 t1 = Class.exp_ (dynamicamic t0) (dynamicamic t1)
  cos_ t0 t1 = Class.cos_ (dynamicamic t0) (dynamicamic t1)
  acos_ t0 t1 = Class.acos_ (dynamicamic t0) (dynamicamic t1)
  cosh_ t0 t1 = Class.cosh_ (dynamicamic t0) (dynamicamic t1)
  sin_ t0 t1 = Class.sin_ (dynamicamic t0) (dynamicamic t1)
  asin_ t0 t1 = Class.asin_ (dynamicamic t0) (dynamicamic t1)
  sinh_ t0 t1 = Class.sinh_ (dynamicamic t0) (dynamicamic t1)
  tan_ t0 t1 = Class.tan_ (dynamicamic t0) (dynamicamic t1)
  atan_ t0 t1 = Class.atan_ (dynamicamic t0) (dynamicamic t1)
  atan2_ t0 t1 t2 = Class.atan2_ (dynamicamic t0) (dynamicamic t1) (dynamicamic t2)
  tanh_ t0 t1 = Class.tanh_ (dynamicamic t0) (dynamicamic t1)
  erf_ t0 t1 = Class.erf_ (dynamicamic t0) (dynamicamic t1)
  erfinv_ t0 t1 = Class.erfinv_ (dynamicamic t0) (dynamicamic t1)
  pow_ t0 t1 = Class.pow_ (dynamicamic t0) (dynamicamic t1)
  tpow_ t0 v t1 = Class.tpow_ (dynamicamic t0) v (dynamicamic t1)
  sqrt_ t0 t1 = Class.sqrt_ (dynamicamic t0) (dynamicamic t1)
  rsqrt_ t0 t1 = Class.rsqrt_ (dynamicamic t0) (dynamicamic t1)
  ceil_ t0 t1 = Class.ceil_ (dynamicamic t0) (dynamicamic t1)
  floor_ t0 t1 = Class.floor_ (dynamicamic t0) (dynamicamic t1)
  round_ t0 t1 = Class.round_ (dynamicamic t0) (dynamicamic t1)
  trunc_ t0 t1 = Class.trunc_ (dynamicamic t0) (dynamicamic t1)
  frac_ t0 t1 = Class.frac_ (dynamicamic t0) (dynamicamic t1)
  lerp_ t0 t1 t2 = Class.lerp_ (dynamicamic t0) (dynamicamic t1) (dynamicamic t2)
  mean_ t0 t1 = Class.mean_ (dynamicamic t0) (dynamicamic t1)
  std_ t0 t1 = Class.std_ (dynamicamic t0) (dynamicamic t1)
  var_ t0 t1 = Class.var_ (dynamicamic t0) (dynamicamic t1)
  norm_ t0 t1 = Class.norm_ (dynamicamic t0) (dynamicamic t1)
  renorm_ t0 t1 = Class.renorm_ (dynamicamic t0) (dynamicamic t1)
  dist t0 t1 = Class.dist (dynamicamic t0) (dynamicamic t1)
  histc_ t0 t1 = Class.histc_ (dynamicamic t0) (dynamicamic t1)
  bhistc_ t0 t1 = Class.bhistc_ (dynamicamic t0) (dynamicamic t1)
  meanall t0 = Class.meanall (dynamicamic t0)
  varall t0 = Class.varall (dynamicamic t0)
  stdall t0 = Class.stdall (dynamicamic t0)
  normall t0 = Class.normall (dynamicamic t0)
  linspace_ t0 = Class.linspace_ (dynamicamic t0)
  logspace_ t0 = Class.logspace_ (dynamic t0)
  rand_ t0 = Class.rand_ (dynamicamic t0)
  randn_ t0 = Class.randn_ (dynamicamic t0)

