module Torch.Class.NN.Static where

import Foreign.C.Types
import Torch.Class.Types
import Torch.Dimensions

class NN t where
  abs_updateOutput             :: Dimensions2 d d' => t d -> t d' -> IO ()
  abs_updateGradInput          :: Dimensions3 d d' d'' => t d -> t d' -> t d'' -> IO ()
  absCriterion_updateOutput    :: Dimensions3 d d' d'' => t d -> t d' -> t d'' -> Bool -> Bool -> IO ()
  absCriterion_updateGradInput :: Dimensions4 d d' d'' d''' => t d -> t d' -> t d'' -> t d''' -> Bool -> Bool -> IO ()
  bCECriterion_updateOutput    :: Dimensions4 d d' d'' d''' => t d -> t d' -> t d'' -> Bool -> t d''' -> Bool -> IO ()
  bCECriterion_updateGradInput :: Dimensions5 d d' d'' d''' d'''' => t d -> t d' -> t d'' -> t d''' -> Bool -> t d'''' -> Bool -> IO ()
  eLU_updateOutput             :: Dimensions2 d d' => t d -> t d -> Double -> Double -> Bool -> IO ()
  eLU_updateGradInput          :: Dimensions3 d d' d'' => t d -> t d' -> t d'' -> Double -> Double -> IO ()

  distKLDivCriterion_updateOutput    :: Dimensions d => t d -> t d -> t d -> Bool -> Bool -> IO ()
  distKLDivCriterion_updateGradInput :: Dimensions d => t d -> t d -> t d -> t d -> Bool -> Bool -> IO ()
  gatedLinear_updateOutput     :: Dimensions d => t d -> t d -> Int -> IO ()
  gatedLinear_updateGradInput  :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  hardTanh_updateOutput        :: Dimensions d => t d -> t d -> Double -> Double -> Bool -> IO ()
  hardTanh_updateGradInput     :: Dimensions d => t d -> t d -> t d -> Double -> Double -> Bool -> IO ()
  im2Col_updateOutput          :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  im2Col_updateGradInput       :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  col2Im_updateOutput          :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  l1Cost_updateOutput          :: Dimensions d => t d -> t d -> IO ()
  l1Cost_updateGradInput       :: Dimensions d => t d -> t d -> t d -> IO ()
  leakyReLU_updateOutput       :: Dimensions d => t d -> t d -> Double -> Bool -> IO ()
  leakyReLU_updateGradInput    :: Dimensions d => t d -> t d -> t d -> Double -> Bool -> IO ()
  gRUFused_updateOutput        :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> t d -> IO ()
  gRUFused_updateGradInput     :: Dimensions d => t d -> t d -> t d -> t d -> t d -> IO ()
  lSTMFused_updateOutput       :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> t d -> IO ()
  lSTMFused_updateGradInput    :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> t d -> IO ()
  logSigmoid_updateOutput      :: Dimensions d => t d -> t d -> t d -> IO ()
  logSigmoid_updateGradInput   :: Dimensions d => t d -> t d -> t d -> t d -> IO ()
  logSoftMax_updateOutput      :: Dimensions d => t d -> t d -> DimReal (t d) -> IO ()
  logSoftMax_updateGradInput   :: Dimensions d => t d -> t d -> t d -> t d -> DimReal (t d) -> IO ()
  marginCriterion_updateOutput                       :: Dimensions d => t d -> t d -> t d -> Bool -> Double -> IO ()
  marginCriterion_updateGradInput                    :: Dimensions d => t d -> t d -> t d -> Bool -> Double -> IO ()
  softMarginCriterion_updateOutput                   :: Dimensions d => t d -> t d -> t d -> Bool -> Bool -> IO ()
  softMarginCriterion_updateGradInput                :: Dimensions d => t d -> t d -> t d -> t d -> Bool -> Bool -> IO ()
  mSECriterion_updateOutput                          :: Dimensions d => t d -> t d -> t d -> Bool -> Bool -> IO ()
  mSECriterion_updateGradInput                       :: Dimensions d => t d -> t d -> t d -> t d -> Bool -> Bool -> IO ()
  pReLU_updateOutput                                 :: Dimensions d => t d -> t d -> t d -> IO ()
  pReLU_updateGradInput                              :: Dimensions d => t d -> t d -> t d -> t d -> IO ()
  pReLU_accGradParameters                            :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Double -> IO ()
  rReLU_updateOutput                                 :: Dimensions d => t d -> t d -> t d -> Double -> Double -> Bool -> Bool -> Generator (t d) -> IO ()
  rReLU_updateGradInput                              :: Dimensions d => t d -> t d -> t d -> t d -> Double -> Double -> Bool -> Bool -> IO ()
  sigmoid_updateOutput                               :: Dimensions d => t d -> t d -> IO ()
  sigmoid_updateGradInput                            :: Dimensions d => t d -> t d -> t d -> IO ()
  smoothL1Criterion_updateOutput                     :: Dimensions d => t d -> t d -> t d -> Bool -> Bool -> IO ()
  smoothL1Criterion_updateGradInput                  :: Dimensions d => t d -> t d -> t d -> t d -> Bool -> Bool -> IO ()
  softMax_updateOutput                               :: Dimensions d => t d -> t d -> DimReal (t d) -> IO ()
  softMax_updateGradInput                            :: Dimensions d => t d -> t d -> t d -> t d -> DimReal (t d) -> IO ()
  softPlus_updateOutput                              :: Dimensions d => t d -> t d -> Double -> Double -> IO ()
  softPlus_updateGradInput                           :: Dimensions d => t d -> t d -> t d -> t d -> Double -> Double -> IO ()
  softShrink_updateOutput                            :: Dimensions d => t d -> t d -> Double -> IO ()
  softShrink_updateGradInput                         :: Dimensions d => t d -> t d -> t d -> Double -> IO ()
  sparseLinear_updateOutput                          :: Dimensions d => t d -> t d -> t d -> t d -> IO ()
  sparseLinear_accGradParameters                     :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Double -> Double -> IO ()
  sparseLinear_zeroGradParameters                    :: Dimensions d => t d -> t d -> t d -> IO ()
  sparseLinear_updateParameters                      :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Double -> IO ()
  sparseLinear_legacyUpdateOutput                    :: Dimensions d => t d -> t d -> t d -> t d -> IO ()
  sparseLinear_legacyAccGradParameters               :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Double -> Double -> IO ()
  sqrt_updateOutput                                  :: Dimensions d => t d -> t d -> Double -> IO ()
  sqrt_updateGradInput                               :: Dimensions d => t d -> t d -> t d -> t d -> IO ()
  square_updateOutput                                :: Dimensions d => t d -> t d -> IO ()
  square_updateGradInput                             :: Dimensions d => t d -> t d -> t d -> IO ()
  tanh_updateOutput                                  :: Dimensions d => t d -> t d -> IO ()
  tanh_updateGradInput                               :: Dimensions d => t d -> t d -> t d -> IO ()
  threshold_updateOutput                             :: Dimensions d => t d -> t d -> Double -> Double -> Bool -> IO ()
  threshold_updateGradInput                          :: Dimensions d => t d -> t d -> t d -> Double -> Double -> Bool -> IO ()
  temporalConvolution_updateOutput                   :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  temporalConvolution_updateGradInput                :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> IO ()
  temporalConvolution_accGradParameters              :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> Double -> IO ()
  temporalRowConvolution_updateOutput                :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Bool -> IO ()
  temporalRowConvolution_updateGradInput             :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Bool -> IO ()
  temporalRowConvolution_accGradParameters           :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Bool -> Double -> IO ()
  temporalUpSamplingNearest_updateOutput             :: Dimensions d => t d -> t d -> Int -> IO ()
  temporalUpSamplingNearest_updateGradInput          :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  temporalUpSamplingLinear_updateOutput              :: Dimensions d => t d -> t d -> Int -> IO ()
  temporalUpSamplingLinear_updateGradInput           :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  batchNormalization_updateOutput                    :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> t d -> t d -> Bool -> Double -> Double -> IO ()
  batchNormalization_backward                        :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> t d -> t d -> t d -> t d -> Bool -> Double -> Double -> IO ()
  spatialConvolutionMM_updateOutput                  :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialConvolutionMM_updateGradInput               :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialConvolutionMM_accGradParameters             :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialConvolutionLocal_updateOutput               :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> IO ()
  spatialConvolutionLocal_updateGradInput            :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> IO ()
  spatialConvolutionLocal_accGradParameters          :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> CLLong -> CLLong -> CLLong -> CLLong -> Double -> IO ()
  spatialAdaptiveAveragePooling_updateOutput         :: Dimensions d => t d -> t d -> Int -> Int -> IO ()
  spatialAdaptiveAveragePooling_updateGradInput      :: Dimensions d => t d -> t d -> t d -> IO ()
  spatialAveragePooling_updateOutput                 :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  spatialAveragePooling_updateGradInput              :: Dimensions d => t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  spatialFullConvolution_updateOutput                :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolution_updateGradInput             :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolution_accGradParameters           :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialDilatedConvolution_updateOutput             :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialDilatedConvolution_updateGradInput          :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialDilatedConvolution_accGradParameters        :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialFullDilatedConvolution_updateOutput         :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullDilatedConvolution_updateGradInput      :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialFullDilatedConvolution_accGradParameters    :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialSubSampling_updateOutput                    :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialSubSampling_updateGradInput                 :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialSubSampling_accGradParameters               :: Dimensions d => t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Double -> IO ()
  spatialUpSamplingNearest_updateOutput              :: Dimensions d => t d -> t d -> Int -> IO ()
  spatialUpSamplingNearest_updateGradInput           :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  spatialUpSamplingBilinear_updateOutput             :: Dimensions d => t d -> t d -> Int -> Int -> IO ()
  spatialUpSamplingBilinear_updateGradInput          :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  spatialGridSamplerBilinear_updateOutput            :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  spatialGridSamplerBilinear_updateGradInput         :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> IO ()
  volumetricGridSamplerBilinear_updateOutput         :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  volumetricGridSamplerBilinear_updateGradInput      :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> IO ()
  volumetricAveragePooling_updateOutput              :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  volumetricAveragePooling_updateGradInput           :: Dimensions d => t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Bool -> Bool -> IO ()
  volumetricConvolution_updateOutput                 :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolution_updateGradInput              :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolution_accGradParameters            :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricFullConvolution_updateOutput             :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullConvolution_updateGradInput          :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullConvolution_accGradParameters        :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricDilatedConvolution_updateOutput          :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricDilatedConvolution_updateGradInput       :: Dimensions d => t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricDilatedConvolution_accGradParameters     :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricFullDilatedConvolution_updateOutput      :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullDilatedConvolution_updateGradInput   :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricFullDilatedConvolution_accGradParameters :: Dimensions d => t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  volumetricAdaptiveAveragePooling_updateOutput      :: Dimensions d => t d -> t d -> Int -> Int -> Int -> IO ()
  volumetricAdaptiveAveragePooling_updateGradInput   :: Dimensions d => t d -> t d -> t d -> IO ()
  spatialReflectionPadding_updateOutput              :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialReflectionPadding_updateGradInput           :: Dimensions d => t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialReplicationPadding_updateOutput             :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialReplicationPadding_updateGradInput          :: Dimensions d => t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  featureLPPooling_updateOutput                      :: Dimensions d => t d -> t d -> Double -> Int -> Int -> Bool -> IO ()
  featureLPPooling_updateGradInput                   :: Dimensions d => t d -> t d -> t d -> t d -> Double -> Int -> Int -> Bool -> IO ()
  volumetricReplicationPadding_updateOutput          :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricReplicationPadding_updateGradInput       :: Dimensions d => t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricUpSamplingNearest_updateOutput           :: Dimensions d => t d -> t d -> Int -> IO ()
  volumetricUpSamplingNearest_updateGradInput        :: Dimensions d => t d -> t d -> t d -> Int -> IO ()
  volumetricUpSamplingTrilinear_updateOutput         :: Dimensions d => t d -> t d -> Int -> Int -> Int -> IO ()
  volumetricUpSamplingTrilinear_updateGradInput      :: Dimensions d => t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  temporalReflectionPadding_updateOutput             :: Dimensions d => t d -> t d -> Int -> Int -> IO ()
  temporalReflectionPadding_updateGradInput          :: Dimensions d => t d -> t d -> t d -> Int -> Int -> IO ()
  temporalReplicationPadding_updateOutput            :: Dimensions d => t d -> t d -> Int -> Int -> IO ()
  temporalReplicationPadding_updateGradInput         :: Dimensions d => t d -> t d -> t d -> Int -> Int -> IO ()

class CPUNN t d where
  unfolded_acc  :: t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  unfolded_copy :: t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_updateOutput :: t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_updateGradInput :: t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  volumetricConvolutionMM_accGradParameters :: t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Double -> IO ()
  temporalSubSampling_updateOutput :: t d -> t d -> t d -> t d -> Int -> Int -> Int -> IO ()
  temporalSubSampling_updateGradInput :: t d -> t d -> t d -> t d -> Int -> Int -> IO ()
  temporalSubSampling_accGradParameters :: t d -> t d -> t d -> t d -> Int -> Int -> Double -> IO ()
  spatialFullConvolutionMap_updateOutput :: t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolutionMap_updateGradInput :: t d -> t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> IO ()
  spatialFullConvolutionMap_accGradParameters :: t d -> t d -> t d -> t d -> t d -> Int -> Int -> Int -> Int -> Double -> IO ()
  hardShrink_updateOutput      :: t d -> t d -> Double -> IO ()
  hardShrink_updateGradInput   :: t d -> t d -> t d -> Double -> IO ()
  col2Im_updateGradInput       :: t d -> t d -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> Int -> IO ()
  linear_updateOutput      :: t d -> t d -> t d -> t d -> t d -> IO ()
  linear_updateGradInput   :: t d -> t d -> t d -> t d -> IO ()
  linear_accGradParameters :: t d -> t d -> t d -> t d -> t d -> t d -> t d -> t d -> Double -> IO ()
  sparseLinear_legacyZeroGradParameters :: t d -> t d -> t d -> IO ()
  sparseLinear_legacyUpdateParameters   :: t d -> t d -> t d -> t d -> t d -> Double -> IO ()
