
-- generated by using spec/Declarations.yaml

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module Torch.Internal.Managed.Native.Native11 where


import Foreign.C.String
import Foreign.C.Types
import Foreign
import Torch.Internal.Type
import Torch.Internal.Class
import Torch.Internal.Cast
import Torch.Internal.Objects
import qualified Torch.Internal.Unmanaged.Native.Native11 as Unmanaged


all_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
all_t = cast1 Unmanaged.all_t

any_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
any_t = cast1 Unmanaged.any_t

renorm_out_ttsls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
renorm_out_ttsls = cast5 Unmanaged.renorm_out_ttsls

renorm_tsls
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
renorm_tsls = cast4 Unmanaged.renorm_tsls

unfold_backward_tllll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> Int64
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
unfold_backward_tllll = cast5 Unmanaged.unfold_backward_tllll

equal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (CBool)
equal_tt = cast2 Unmanaged.equal_tt

pow_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_ttt = cast3 Unmanaged.pow_out_ttt

pow_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_tt = cast2 Unmanaged.pow_tt

pow_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_tst = cast3 Unmanaged.pow_out_tst

pow_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_st = cast2 Unmanaged.pow_st

pow_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
pow_out_tts = cast3 Unmanaged.pow_out_tts

pow_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
pow_ts = cast2 Unmanaged.pow_ts

float_power_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
float_power_out_ttt = cast3 Unmanaged.float_power_out_ttt

float_power_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
float_power_tt = cast2 Unmanaged.float_power_tt

float_power_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
float_power_out_tst = cast3 Unmanaged.float_power_out_tst

float_power_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
float_power_st = cast2 Unmanaged.float_power_st

float_power_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
float_power_out_tts = cast3 Unmanaged.float_power_out_tts

float_power_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
float_power_ts = cast2 Unmanaged.float_power_ts

normal_out_ttdG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_ttdG = cast4 Unmanaged.normal_out_ttdG

normal_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_out_ttd = cast3 Unmanaged.normal_out_ttd

normal_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tt = cast2 Unmanaged.normal_out_tt

normal_tdG
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_tdG = cast3 Unmanaged.normal_tdG

normal_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_td = cast2 Unmanaged.normal_td

normal_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_t = cast1 Unmanaged.normal_t

normal_out_tdtG
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tdtG = cast4 Unmanaged.normal_out_tdtG

normal_out_tdt
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tdt = cast3 Unmanaged.normal_out_tdt

normal_dtG
  :: CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_dtG = cast3 Unmanaged.normal_dtG

normal_dt
  :: CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_dt = cast2 Unmanaged.normal_dt

normal_out_tttG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tttG = cast4 Unmanaged.normal_out_tttG

normal_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_ttt = cast3 Unmanaged.normal_out_ttt

normal_ttG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ttG = cast3 Unmanaged.normal_ttG

normal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_tt = cast2 Unmanaged.normal_tt

normal_ddlGo
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> ForeignPtr TensorOptions
  -> IO (ForeignPtr Tensor)
normal_ddlGo = cast5 Unmanaged.normal_ddlGo

normal_ddlG
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ddlG = cast4 Unmanaged.normal_ddlG

normal_ddl
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_ddl = cast3 Unmanaged.normal_ddl

normal_out_tddlG
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tddlG = cast5 Unmanaged.normal_out_tddlG

normal_out_tddl
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_out_tddl = cast4 Unmanaged.normal_out_tddl

alias_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
alias_t = cast1 Unmanaged.alias_t

_index_copy__tltt
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_index_copy__tltt = cast4 Unmanaged._index_copy__tltt

_cumsum_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_tl = cast2 Unmanaged._cumsum_tl

_cumsum_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_out_ttl = cast3 Unmanaged._cumsum_out_ttl

_cumprod_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_tl = cast2 Unmanaged._cumprod_tl

_cumprod_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_out_ttl = cast3 Unmanaged._cumprod_out_ttl

_var_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_var_tb = cast2 Unmanaged._var_tb

_var_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_var_t = cast1 Unmanaged._var_t

_std_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_std_tb = cast2 Unmanaged._std_tb

_std_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_std_t = cast1 Unmanaged._std_t

_amp_foreach_non_finite_check_and_unscale__ltt
  :: ForeignPtr TensorList
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (())
_amp_foreach_non_finite_check_and_unscale__ltt = cast3 Unmanaged._amp_foreach_non_finite_check_and_unscale__ltt

_amp_update_scale_tttddl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
_amp_update_scale_tttddl = cast6 Unmanaged._amp_update_scale_tttddl

_cat_ll
  :: ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_ll = cast2 Unmanaged._cat_ll

_cat_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_l = cast1 Unmanaged._cat_l

_cat_out_tll
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_out_tll = cast3 Unmanaged._cat_out_tll

_cat_out_tl
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_out_tl = cast2 Unmanaged._cat_out_tl

_foreach_add_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_add_ls = cast2 Unmanaged._foreach_add_ls

_foreach_add__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_add__ls = cast2 Unmanaged._foreach_add__ls

_foreach_sub_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_sub_ls = cast2 Unmanaged._foreach_sub_ls

_foreach_sub__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_sub__ls = cast2 Unmanaged._foreach_sub__ls

_foreach_mul_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_mul_ls = cast2 Unmanaged._foreach_mul_ls

_foreach_mul__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_mul__ls = cast2 Unmanaged._foreach_mul__ls

_foreach_div_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_div_ls = cast2 Unmanaged._foreach_div_ls

_foreach_div__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_div__ls = cast2 Unmanaged._foreach_div__ls

_foreach_add_lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_add_lls = cast3 Unmanaged._foreach_add_lls

_foreach_add_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_add_ll = cast2 Unmanaged._foreach_add_ll

_foreach_add__lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_add__lls = cast3 Unmanaged._foreach_add__lls

_foreach_add__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_add__ll = cast2 Unmanaged._foreach_add__ll

_foreach_sub_lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_sub_lls = cast3 Unmanaged._foreach_sub_lls

_foreach_sub_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sub_ll = cast2 Unmanaged._foreach_sub_ll

_foreach_sub__lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_sub__lls = cast3 Unmanaged._foreach_sub__lls

_foreach_sub__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_sub__ll = cast2 Unmanaged._foreach_sub__ll

_foreach_mul_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_mul_ll = cast2 Unmanaged._foreach_mul_ll

_foreach_mul__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_mul__ll = cast2 Unmanaged._foreach_mul__ll

_foreach_div_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_div_ll = cast2 Unmanaged._foreach_div_ll

_foreach_div__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_div__ll = cast2 Unmanaged._foreach_div__ll

_foreach_add_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_add_la = cast2 Unmanaged._foreach_add_la

_foreach_add__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_add__la = cast2 Unmanaged._foreach_add__la

_foreach_sub_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_sub_la = cast2 Unmanaged._foreach_sub_la

_foreach_sub__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_sub__la = cast2 Unmanaged._foreach_sub__la

_foreach_div_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_div_la = cast2 Unmanaged._foreach_div_la

_foreach_div__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_div__la = cast2 Unmanaged._foreach_div__la

_foreach_mul_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_mul_la = cast2 Unmanaged._foreach_mul_la

_foreach_mul__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_mul__la = cast2 Unmanaged._foreach_mul__la

_foreach_exp_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_exp_l = cast1 Unmanaged._foreach_exp_l

_foreach_zero__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_zero__l = cast1 Unmanaged._foreach_zero__l

_foreach_exp__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_exp__l = cast1 Unmanaged._foreach_exp__l

_foreach_sqrt_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sqrt_l = cast1 Unmanaged._foreach_sqrt_l

_foreach_sqrt__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_sqrt__l = cast1 Unmanaged._foreach_sqrt__l

_foreach_abs_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_abs_l = cast1 Unmanaged._foreach_abs_l

_foreach_abs__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_abs__l = cast1 Unmanaged._foreach_abs__l

_foreach_acos_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_acos_l = cast1 Unmanaged._foreach_acos_l

_foreach_acos__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_acos__l = cast1 Unmanaged._foreach_acos__l

_foreach_asin_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_asin_l = cast1 Unmanaged._foreach_asin_l

_foreach_asin__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_asin__l = cast1 Unmanaged._foreach_asin__l

_foreach_atan_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_atan_l = cast1 Unmanaged._foreach_atan_l

_foreach_atan__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_atan__l = cast1 Unmanaged._foreach_atan__l

_foreach_ceil_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_ceil_l = cast1 Unmanaged._foreach_ceil_l

_foreach_ceil__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_ceil__l = cast1 Unmanaged._foreach_ceil__l

_foreach_cos_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_cos_l = cast1 Unmanaged._foreach_cos_l

_foreach_cos__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_cos__l = cast1 Unmanaged._foreach_cos__l

_foreach_cosh_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_cosh_l = cast1 Unmanaged._foreach_cosh_l

_foreach_cosh__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_cosh__l = cast1 Unmanaged._foreach_cosh__l

_foreach_erf_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_erf_l = cast1 Unmanaged._foreach_erf_l

_foreach_erf__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_erf__l = cast1 Unmanaged._foreach_erf__l

_foreach_erfc_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_erfc_l = cast1 Unmanaged._foreach_erfc_l

_foreach_erfc__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_erfc__l = cast1 Unmanaged._foreach_erfc__l

_foreach_expm1_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_expm1_l = cast1 Unmanaged._foreach_expm1_l

_foreach_expm1__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_expm1__l = cast1 Unmanaged._foreach_expm1__l

_foreach_floor_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_floor_l = cast1 Unmanaged._foreach_floor_l

_foreach_floor__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_floor__l = cast1 Unmanaged._foreach_floor__l

_foreach_log_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_log_l = cast1 Unmanaged._foreach_log_l

_foreach_log__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_log__l = cast1 Unmanaged._foreach_log__l

_foreach_log10_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_log10_l = cast1 Unmanaged._foreach_log10_l

_foreach_log10__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_log10__l = cast1 Unmanaged._foreach_log10__l

_foreach_log1p_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_log1p_l = cast1 Unmanaged._foreach_log1p_l

_foreach_log1p__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_log1p__l = cast1 Unmanaged._foreach_log1p__l

_foreach_log2_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_log2_l = cast1 Unmanaged._foreach_log2_l

_foreach_log2__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_log2__l = cast1 Unmanaged._foreach_log2__l

_foreach_neg_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_neg_l = cast1 Unmanaged._foreach_neg_l

_foreach_neg__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_neg__l = cast1 Unmanaged._foreach_neg__l

_foreach_tan_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_tan_l = cast1 Unmanaged._foreach_tan_l

_foreach_tan__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_tan__l = cast1 Unmanaged._foreach_tan__l

_foreach_tanh_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_tanh_l = cast1 Unmanaged._foreach_tanh_l

_foreach_tanh__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_tanh__l = cast1 Unmanaged._foreach_tanh__l

_foreach_sin_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sin_l = cast1 Unmanaged._foreach_sin_l

_foreach_sin__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_sin__l = cast1 Unmanaged._foreach_sin__l

_foreach_sinh_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sinh_l = cast1 Unmanaged._foreach_sinh_l

_foreach_sinh__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_sinh__l = cast1 Unmanaged._foreach_sinh__l

_foreach_round_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_round_l = cast1 Unmanaged._foreach_round_l

_foreach_round__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_round__l = cast1 Unmanaged._foreach_round__l

_foreach_lgamma_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_lgamma_l = cast1 Unmanaged._foreach_lgamma_l

_foreach_lgamma__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_lgamma__l = cast1 Unmanaged._foreach_lgamma__l

_foreach_frac_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_frac_l = cast1 Unmanaged._foreach_frac_l

_foreach_frac__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_frac__l = cast1 Unmanaged._foreach_frac__l

_foreach_reciprocal_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_reciprocal_l = cast1 Unmanaged._foreach_reciprocal_l

_foreach_reciprocal__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_reciprocal__l = cast1 Unmanaged._foreach_reciprocal__l

_foreach_sigmoid_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sigmoid_l = cast1 Unmanaged._foreach_sigmoid_l

_foreach_sigmoid__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_sigmoid__l = cast1 Unmanaged._foreach_sigmoid__l

_foreach_trunc_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_trunc_l = cast1 Unmanaged._foreach_trunc_l

_foreach_trunc__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_trunc__l = cast1 Unmanaged._foreach_trunc__l

_foreach_addcdiv__llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_addcdiv__llls = cast4 Unmanaged._foreach_addcdiv__llls

_foreach_addcdiv__lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_addcdiv__lll = cast3 Unmanaged._foreach_addcdiv__lll

_foreach_addcmul__llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_addcmul__llls = cast4 Unmanaged._foreach_addcmul__llls

_foreach_addcmul__lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_addcmul__lll = cast3 Unmanaged._foreach_addcmul__lll

_foreach_addcdiv__llla
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_addcdiv__llla = cast4 Unmanaged._foreach_addcdiv__llla

_foreach_addcmul__llla
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_addcmul__llla = cast4 Unmanaged._foreach_addcmul__llla

_foreach_addcdiv_llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_addcdiv_llls = cast4 Unmanaged._foreach_addcdiv_llls

_foreach_addcdiv_lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_addcdiv_lll = cast3 Unmanaged._foreach_addcdiv_lll

_foreach_addcmul_llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_addcmul_llls = cast4 Unmanaged._foreach_addcmul_llls

_foreach_addcmul_lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_addcmul_lll = cast3 Unmanaged._foreach_addcmul_lll

_foreach_addcdiv_llla
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_addcdiv_llla = cast4 Unmanaged._foreach_addcdiv_llla

_foreach_addcmul_llla
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_addcmul_llla = cast4 Unmanaged._foreach_addcmul_llla

_foreach_maximum_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_maximum_ll = cast2 Unmanaged._foreach_maximum_ll

_foreach_minimum_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_minimum_ll = cast2 Unmanaged._foreach_minimum_ll

_mode_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tlb = cast3 Unmanaged._mode_tlb

_mode_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tl = cast2 Unmanaged._mode_tl

_mode_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_t = cast1 Unmanaged._mode_t

_mode_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttlb = cast5 Unmanaged._mode_out_tttlb

_mode_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttl = cast4 Unmanaged._mode_out_tttl

_mode_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_ttt = cast3 Unmanaged._mode_out_ttt

bucketize_ttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_ttbb = cast4 Unmanaged.bucketize_ttbb

bucketize_ttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_ttb = cast3 Unmanaged.bucketize_ttb

bucketize_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_tt = cast2 Unmanaged.bucketize_tt

bucketize_out_tttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_out_tttbb = cast5 Unmanaged.bucketize_out_tttbb

bucketize_out_tttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_out_tttb = cast4 Unmanaged.bucketize_out_tttb

bucketize_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_out_ttt = cast3 Unmanaged.bucketize_out_ttt

bucketize_stbb
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_stbb = cast4 Unmanaged.bucketize_stbb

bucketize_stb
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_stb = cast3 Unmanaged.bucketize_stb

bucketize_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_st = cast2 Unmanaged.bucketize_st

searchsorted_ttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_ttbb = cast4 Unmanaged.searchsorted_ttbb

searchsorted_ttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_ttb = cast3 Unmanaged.searchsorted_ttb

searchsorted_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
searchsorted_tt = cast2 Unmanaged.searchsorted_tt

searchsorted_out_tttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_out_tttbb = cast5 Unmanaged.searchsorted_out_tttbb

searchsorted_out_tttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_out_tttb = cast4 Unmanaged.searchsorted_out_tttb

searchsorted_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
searchsorted_out_ttt = cast3 Unmanaged.searchsorted_out_ttt

