
-- generated by using spec/Declarations.yaml

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module Torch.Internal.Managed.Native.Native12 where


import Foreign.C.String
import Foreign.C.Types
import Foreign
import Torch.Internal.Type
import Torch.Internal.Class
import Torch.Internal.Cast
import Torch.Internal.Objects
import qualified Torch.Internal.Unmanaged.Native.Native12 as Unmanaged


_cumsum_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_tl = cast2 Unmanaged._cumsum_tl

_cumsum_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_out_ttl = cast3 Unmanaged._cumsum_out_ttl

_cumprod_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_tl = cast2 Unmanaged._cumprod_tl

_cumprod_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_out_ttl = cast3 Unmanaged._cumprod_out_ttl

_var_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_var_tb = cast2 Unmanaged._var_tb

_var_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_var_t = cast1 Unmanaged._var_t

_std_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_std_tb = cast2 Unmanaged._std_tb

_std_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_std_t = cast1 Unmanaged._std_t

_amp_non_finite_check_and_unscale__ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (())
_amp_non_finite_check_and_unscale__ttt = cast3 Unmanaged._amp_non_finite_check_and_unscale__ttt

_amp_update_scale_tttddl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
_amp_update_scale_tttddl = cast6 Unmanaged._amp_update_scale_tttddl

_cat_ll
  :: ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_ll = cast2 Unmanaged._cat_ll

_cat_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_l = cast1 Unmanaged._cat_l

_cat_out_tll
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_out_tll = cast3 Unmanaged._cat_out_tll

_cat_out_tl
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_out_tl = cast2 Unmanaged._cat_out_tl

_foreach_add_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_add_ls = cast2 Unmanaged._foreach_add_ls

_foreach_add__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_add__ls = cast2 Unmanaged._foreach_add__ls

_foreach_sub_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_sub_ls = cast2 Unmanaged._foreach_sub_ls

_foreach_sub__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_sub__ls = cast2 Unmanaged._foreach_sub__ls

_foreach_mul_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_mul_ls = cast2 Unmanaged._foreach_mul_ls

_foreach_mul__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_mul__ls = cast2 Unmanaged._foreach_mul__ls

_foreach_div_ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_div_ls = cast2 Unmanaged._foreach_div_ls

_foreach_div__ls
  :: ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_div__ls = cast2 Unmanaged._foreach_div__ls

_foreach_add_lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_add_lls = cast3 Unmanaged._foreach_add_lls

_foreach_add_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_add_ll = cast2 Unmanaged._foreach_add_ll

_foreach_add__lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_add__lls = cast3 Unmanaged._foreach_add__lls

_foreach_add__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_add__ll = cast2 Unmanaged._foreach_add__ll

_foreach_sub_lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_sub_lls = cast3 Unmanaged._foreach_sub_lls

_foreach_sub_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sub_ll = cast2 Unmanaged._foreach_sub_ll

_foreach_sub__lls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_sub__lls = cast3 Unmanaged._foreach_sub__lls

_foreach_sub__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_sub__ll = cast2 Unmanaged._foreach_sub__ll

_foreach_mul_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_mul_ll = cast2 Unmanaged._foreach_mul_ll

_foreach_mul__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_mul__ll = cast2 Unmanaged._foreach_mul__ll

_foreach_div_ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_div_ll = cast2 Unmanaged._foreach_div_ll

_foreach_div__ll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_div__ll = cast2 Unmanaged._foreach_div__ll

_foreach_add_scalar_list_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_add_scalar_list_la = cast2 Unmanaged._foreach_add_scalar_list_la

_foreach_add_scalar_list__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_add_scalar_list__la = cast2 Unmanaged._foreach_add_scalar_list__la

_foreach_sub_scalar_list_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_sub_scalar_list_la = cast2 Unmanaged._foreach_sub_scalar_list_la

_foreach_sub_scalar_list__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_sub_scalar_list__la = cast2 Unmanaged._foreach_sub_scalar_list__la

_foreach_div_scalar_list_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_div_scalar_list_la = cast2 Unmanaged._foreach_div_scalar_list_la

_foreach_div_scalar_list__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_div_scalar_list__la = cast2 Unmanaged._foreach_div_scalar_list__la

_foreach_mul_scalar_list_la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (ForeignPtr TensorList)
_foreach_mul_scalar_list_la = cast2 Unmanaged._foreach_mul_scalar_list_la

_foreach_mul_scalar_list__la
  :: ForeignPtr TensorList
  -> ForeignPtr (StdVector CDouble)
  -> IO (())
_foreach_mul_scalar_list__la = cast2 Unmanaged._foreach_mul_scalar_list__la

_foreach_exp_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_exp_l = cast1 Unmanaged._foreach_exp_l

_foreach_exp__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_exp__l = cast1 Unmanaged._foreach_exp__l

_foreach_sqrt_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_sqrt_l = cast1 Unmanaged._foreach_sqrt_l

_foreach_sqrt__l
  :: ForeignPtr TensorList
  -> IO (())
_foreach_sqrt__l = cast1 Unmanaged._foreach_sqrt__l

_foreach_addcdiv__llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_addcdiv__llls = cast4 Unmanaged._foreach_addcdiv__llls

_foreach_addcdiv__lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_addcdiv__lll = cast3 Unmanaged._foreach_addcdiv__lll

_foreach_addcmul__llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (())
_foreach_addcmul__llls = cast4 Unmanaged._foreach_addcmul__llls

_foreach_addcmul__lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (())
_foreach_addcmul__lll = cast3 Unmanaged._foreach_addcmul__lll

_foreach_addcdiv_llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_addcdiv_llls = cast4 Unmanaged._foreach_addcdiv_llls

_foreach_addcdiv_lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_addcdiv_lll = cast3 Unmanaged._foreach_addcdiv_lll

_foreach_addcmul_llls
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr Scalar
  -> IO (ForeignPtr TensorList)
_foreach_addcmul_llls = cast4 Unmanaged._foreach_addcmul_llls

_foreach_addcmul_lll
  :: ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> ForeignPtr TensorList
  -> IO (ForeignPtr TensorList)
_foreach_addcmul_lll = cast3 Unmanaged._foreach_addcmul_lll

_mode_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tlb = cast3 Unmanaged._mode_tlb

_mode_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tl = cast2 Unmanaged._mode_tl

_mode_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_t = cast1 Unmanaged._mode_t

_mode_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttlb = cast5 Unmanaged._mode_out_tttlb

_mode_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttl = cast4 Unmanaged._mode_out_tttl

_mode_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_ttt = cast3 Unmanaged._mode_out_ttt

bucketize_ttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_ttbb = cast4 Unmanaged.bucketize_ttbb

bucketize_ttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_ttb = cast3 Unmanaged.bucketize_ttb

bucketize_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_tt = cast2 Unmanaged.bucketize_tt

bucketize_out_tttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_out_tttbb = cast5 Unmanaged.bucketize_out_tttbb

bucketize_out_tttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_out_tttb = cast4 Unmanaged.bucketize_out_tttb

bucketize_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_out_ttt = cast3 Unmanaged.bucketize_out_ttt

bucketize_stbb
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_stbb = cast4 Unmanaged.bucketize_stbb

bucketize_stb
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
bucketize_stb = cast3 Unmanaged.bucketize_stb

bucketize_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
bucketize_st = cast2 Unmanaged.bucketize_st

searchsorted_ttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_ttbb = cast4 Unmanaged.searchsorted_ttbb

searchsorted_ttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_ttb = cast3 Unmanaged.searchsorted_ttb

searchsorted_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
searchsorted_tt = cast2 Unmanaged.searchsorted_tt

searchsorted_out_tttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_out_tttbb = cast5 Unmanaged.searchsorted_out_tttbb

searchsorted_out_tttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_out_tttb = cast4 Unmanaged.searchsorted_out_tttb

searchsorted_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
searchsorted_out_ttt = cast3 Unmanaged.searchsorted_out_ttt

searchsorted_tsbb
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_tsbb = cast4 Unmanaged.searchsorted_tsbb

searchsorted_tsb
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> CBool
  -> IO (ForeignPtr Tensor)
searchsorted_tsb = cast3 Unmanaged.searchsorted_tsb

searchsorted_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
searchsorted_ts = cast2 Unmanaged.searchsorted_ts

mse_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_out_tttl = cast4 Unmanaged.mse_loss_out_tttl

mse_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
mse_loss_out_ttt = cast3 Unmanaged.mse_loss_out_ttt

mse_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_ttl = cast3 Unmanaged.mse_loss_ttl

mse_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
mse_loss_tt = cast2 Unmanaged.mse_loss_tt

mse_loss_backward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_backward_out_ttttl = cast5 Unmanaged.mse_loss_backward_out_ttttl

mse_loss_backward_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_backward_tttl = cast4 Unmanaged.mse_loss_backward_tttl

l1_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_out_tttl = cast4 Unmanaged.l1_loss_out_tttl

l1_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
l1_loss_out_ttt = cast3 Unmanaged.l1_loss_out_ttt

l1_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_ttl = cast3 Unmanaged.l1_loss_ttl

l1_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
l1_loss_tt = cast2 Unmanaged.l1_loss_tt

l1_loss_backward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_backward_out_ttttl = cast5 Unmanaged.l1_loss_backward_out_ttttl

l1_loss_backward_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_backward_tttl = cast4 Unmanaged.l1_loss_backward_tttl

multi_margin_loss_out_tttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttsstl = cast7 Unmanaged.multi_margin_loss_out_tttsstl

multi_margin_loss_out_tttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttsst = cast6 Unmanaged.multi_margin_loss_out_tttsst

multi_margin_loss_out_tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttss = cast5 Unmanaged.multi_margin_loss_out_tttss

multi_margin_loss_out_ttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_ttts = cast4 Unmanaged.multi_margin_loss_out_ttts

multi_margin_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_ttt = cast3 Unmanaged.multi_margin_loss_out_ttt

multi_margin_loss_ttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttsstl = cast6 Unmanaged.multi_margin_loss_ttsstl

multi_margin_loss_ttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttsst = cast5 Unmanaged.multi_margin_loss_ttsst

multi_margin_loss_ttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttss = cast4 Unmanaged.multi_margin_loss_ttss

multi_margin_loss_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_tts = cast3 Unmanaged.multi_margin_loss_tts

multi_margin_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_tt = cast2 Unmanaged.multi_margin_loss_tt

multi_margin_loss_backward_out_ttttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttsstl = cast8 Unmanaged.multi_margin_loss_backward_out_ttttsstl

multi_margin_loss_backward_out_ttttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttsst = cast7 Unmanaged.multi_margin_loss_backward_out_ttttsst

multi_margin_loss_backward_out_ttttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttss = cast6 Unmanaged.multi_margin_loss_backward_out_ttttss

multi_margin_loss_backward_tttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttsstl = cast7 Unmanaged.multi_margin_loss_backward_tttsstl

multi_margin_loss_backward_tttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttsst = cast6 Unmanaged.multi_margin_loss_backward_tttsst

multi_margin_loss_backward_tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttss = cast5 Unmanaged.multi_margin_loss_backward_tttss

multilabel_margin_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_out_tttl = cast4 Unmanaged.multilabel_margin_loss_out_tttl

multilabel_margin_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_out_ttt = cast3 Unmanaged.multilabel_margin_loss_out_ttt

multilabel_margin_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_ttl = cast3 Unmanaged.multilabel_margin_loss_ttl

multilabel_margin_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_tt = cast2 Unmanaged.multilabel_margin_loss_tt

multilabel_margin_loss_forward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
multilabel_margin_loss_forward_out_ttttl = cast5 Unmanaged.multilabel_margin_loss_forward_out_ttttl

multilabel_margin_loss_forward_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
multilabel_margin_loss_forward_ttl = cast3 Unmanaged.multilabel_margin_loss_forward_ttl

multilabel_margin_loss_backward_out_ttttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_backward_out_ttttlt = cast6 Unmanaged.multilabel_margin_loss_backward_out_ttttlt

multilabel_margin_loss_backward_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_backward_tttlt = cast5 Unmanaged.multilabel_margin_loss_backward_tttlt

nll_loss_out_ttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttttll = cast6 Unmanaged.nll_loss_out_ttttll

nll_loss_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttttl = cast5 Unmanaged.nll_loss_out_ttttl

nll_loss_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_out_tttt = cast4 Unmanaged.nll_loss_out_tttt

nll_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttt = cast3 Unmanaged.nll_loss_out_ttt

nll_loss_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_tttll = cast5 Unmanaged.nll_loss_tttll

nll_loss_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_tttl = cast4 Unmanaged.nll_loss_tttl

nll_loss_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_ttt = cast3 Unmanaged.nll_loss_ttt

nll_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_tt = cast2 Unmanaged.nll_loss_tt

nll_loss_forward_out_tttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss_forward_out_tttttll = cast7 Unmanaged.nll_loss_forward_out_tttttll

nll_loss_forward_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss_forward_tttll = cast5 Unmanaged.nll_loss_forward_tttll

nll_loss_backward_out_tttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_backward_out_tttttllt = cast8 Unmanaged.nll_loss_backward_out_tttttllt

nll_loss_backward_ttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_backward_ttttllt = cast7 Unmanaged.nll_loss_backward_ttttllt

nll_loss2d_out_ttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttttll = cast6 Unmanaged.nll_loss2d_out_ttttll

nll_loss2d_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttttl = cast5 Unmanaged.nll_loss2d_out_ttttl

nll_loss2d_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_tttt = cast4 Unmanaged.nll_loss2d_out_tttt

nll_loss2d_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttt = cast3 Unmanaged.nll_loss2d_out_ttt

nll_loss2d_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_tttll = cast5 Unmanaged.nll_loss2d_tttll

nll_loss2d_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_tttl = cast4 Unmanaged.nll_loss2d_tttl

nll_loss2d_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_ttt = cast3 Unmanaged.nll_loss2d_ttt

nll_loss2d_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_tt = cast2 Unmanaged.nll_loss2d_tt

nll_loss2d_forward_out_tttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss2d_forward_out_tttttll = cast7 Unmanaged.nll_loss2d_forward_out_tttttll

nll_loss2d_forward_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss2d_forward_tttll = cast5 Unmanaged.nll_loss2d_forward_tttll

nll_loss2d_backward_out_tttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_backward_out_tttttllt = cast8 Unmanaged.nll_loss2d_backward_out_tttttllt

nll_loss2d_backward_ttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_backward_ttttllt = cast7 Unmanaged.nll_loss2d_backward_ttttllt

smooth_l1_loss_out_tttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CDouble
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_out_tttld = cast5 Unmanaged.smooth_l1_loss_out_tttld

smooth_l1_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_out_tttl = cast4 Unmanaged.smooth_l1_loss_out_tttl

smooth_l1_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_out_ttt = cast3 Unmanaged.smooth_l1_loss_out_ttt

smooth_l1_loss_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CDouble
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_ttld = cast4 Unmanaged.smooth_l1_loss_ttld

smooth_l1_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_ttl = cast3 Unmanaged.smooth_l1_loss_ttl

smooth_l1_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_tt = cast2 Unmanaged.smooth_l1_loss_tt

smooth_l1_loss_backward_out_ttttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CDouble
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_backward_out_ttttld = cast6 Unmanaged.smooth_l1_loss_backward_out_ttttld

smooth_l1_loss_backward_tttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CDouble
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_backward_tttld = cast5 Unmanaged.smooth_l1_loss_backward_tttld

soft_margin_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
soft_margin_loss_out_tttl = cast4 Unmanaged.soft_margin_loss_out_tttl

soft_margin_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
soft_margin_loss_out_ttt = cast3 Unmanaged.soft_margin_loss_out_ttt

soft_margin_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
soft_margin_loss_ttl = cast3 Unmanaged.soft_margin_loss_ttl

soft_margin_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
soft_margin_loss_tt = cast2 Unmanaged.soft_margin_loss_tt

soft_margin_loss_backward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
soft_margin_loss_backward_out_ttttl = cast5 Unmanaged.soft_margin_loss_backward_out_ttttl

soft_margin_loss_backward_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
soft_margin_loss_backward_tttl = cast4 Unmanaged.soft_margin_loss_backward_tttl

elu_out_ttsss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
elu_out_ttsss = cast5 Unmanaged.elu_out_ttsss

