
-- generated by using spec/Declarations.yaml

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module Torch.Internal.Managed.Native.Native12 where


import Foreign.C.String
import Foreign.C.Types
import Foreign
import Torch.Internal.Type
import Torch.Internal.Class
import Torch.Internal.Cast
import qualified Torch.Internal.Unmanaged.Native as Unmanaged
import Torch.Internal.Unmanaged.Type.Generator
import Torch.Internal.Unmanaged.Type.IntArray
import Torch.Internal.Unmanaged.Type.Scalar
import Torch.Internal.Unmanaged.Type.Storage
import Torch.Internal.Unmanaged.Type.Tensor
import Torch.Internal.Unmanaged.Type.TensorList
import Torch.Internal.Unmanaged.Type.TensorOptions
import Torch.Internal.Unmanaged.Type.Tuple
import Torch.Internal.Unmanaged.Type.StdString
import Torch.Internal.Unmanaged.Type.StdArray
import Torch.Internal.Unmanaged.Type.Dimname
import Torch.Internal.Unmanaged.Type.DimnameList


renorm_tsls
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
renorm_tsls = cast4 Unmanaged.renorm_tsls

equal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (CBool)
equal_tt = cast2 Unmanaged.equal_tt

pow_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_ttt = cast3 Unmanaged.pow_out_ttt

pow_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_tt = cast2 Unmanaged.pow_tt

pow_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_tst = cast3 Unmanaged.pow_out_tst

pow_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_st = cast2 Unmanaged.pow_st

normal_out_ttdp
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_ttdp = cast4 Unmanaged.normal_out_ttdp

normal_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_out_ttd = cast3 Unmanaged.normal_out_ttd

normal_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tt = cast2 Unmanaged.normal_out_tt

normal_tdp
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_tdp = cast3 Unmanaged.normal_tdp

normal_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_td = cast2 Unmanaged.normal_td

normal_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_t = cast1 Unmanaged.normal_t

normal_out_tdtp
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tdtp = cast4 Unmanaged.normal_out_tdtp

normal_out_tdt
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tdt = cast3 Unmanaged.normal_out_tdt

normal_dtp
  :: CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_dtp = cast3 Unmanaged.normal_dtp

normal_dt
  :: CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_dt = cast2 Unmanaged.normal_dt

normal_out_tttp
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tttp = cast4 Unmanaged.normal_out_tttp

normal_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_ttt = cast3 Unmanaged.normal_out_ttt

normal_ttp
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ttp = cast3 Unmanaged.normal_ttp

normal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_tt = cast2 Unmanaged.normal_tt

normal_ddlpo
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> ForeignPtr TensorOptions
  -> IO (ForeignPtr Tensor)
normal_ddlpo = cast5 Unmanaged.normal_ddlpo

normal_ddlp
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ddlp = cast4 Unmanaged.normal_ddlp

normal_ddl
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_ddl = cast3 Unmanaged.normal_ddl

normal_out_tddlp
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tddlp = cast5 Unmanaged.normal_out_tddlp

normal_out_tddl
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_out_tddl = cast4 Unmanaged.normal_out_tddl

alias_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
alias_t = cast1 Unmanaged.alias_t

_addr_tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr_tttss = cast5 Unmanaged._addr_tttss

_addr_ttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr_ttts = cast4 Unmanaged._addr_ttts

_addr_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_addr_ttt = cast3 Unmanaged._addr_ttt

_addr__tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr__tttss = cast5 Unmanaged._addr__tttss

_addr__ttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr__ttts = cast4 Unmanaged._addr__ttts

_addr__ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_addr__ttt = cast3 Unmanaged._addr__ttt

_addr_out_ttttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr_out_ttttss = cast6 Unmanaged._addr_out_ttttss

_addr_out_tttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
_addr_out_tttts = cast5 Unmanaged._addr_out_tttts

_addr_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_addr_out_tttt = cast4 Unmanaged._addr_out_tttt

_index_copy__tltt
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_index_copy__tltt = cast4 Unmanaged._index_copy__tltt

_cumsum_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_tl = cast2 Unmanaged._cumsum_tl

_cumsum_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumsum_out_ttl = cast3 Unmanaged._cumsum_out_ttl

_cumprod_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_tl = cast2 Unmanaged._cumprod_tl

_cumprod_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_cumprod_out_ttl = cast3 Unmanaged._cumprod_out_ttl

_var_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_var_tb = cast2 Unmanaged._var_tb

_var_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_var_t = cast1 Unmanaged._var_t

_std_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
_std_tb = cast2 Unmanaged._std_tb

_std_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_std_t = cast1 Unmanaged._std_t

_amp_non_finite_check_and_unscale__ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (())
_amp_non_finite_check_and_unscale__ttt = cast3 Unmanaged._amp_non_finite_check_and_unscale__ttt

_amp_update_scale_tttddl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
_amp_update_scale_tttddl = cast6 Unmanaged._amp_update_scale_tttddl

_cat_ll
  :: ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_ll = cast2 Unmanaged._cat_ll

_cat_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_l = cast1 Unmanaged._cat_l

_cat_out_tll
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> Int64
  -> IO (ForeignPtr Tensor)
_cat_out_tll = cast3 Unmanaged._cat_out_tll

_cat_out_tl
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
_cat_out_tl = cast2 Unmanaged._cat_out_tl

_mode_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tlb = cast3 Unmanaged._mode_tlb

_mode_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_tl = cast2 Unmanaged._mode_tl

_mode_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_t = cast1 Unmanaged._mode_t

_mode_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttlb = cast5 Unmanaged._mode_out_tttlb

_mode_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_tttl = cast4 Unmanaged._mode_out_tttl

_mode_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_mode_out_ttt = cast3 Unmanaged._mode_out_ttt

_max_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_max_tlb = cast3 Unmanaged._max_tlb

_max_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_max_tl = cast2 Unmanaged._max_tl

_max_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_max_out_tttlb = cast5 Unmanaged._max_out_tttlb

_max_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_max_out_tttl = cast4 Unmanaged._max_out_tttl

_min_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_min_tlb = cast3 Unmanaged._min_tlb

_min_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_min_tl = cast2 Unmanaged._min_tl

_min_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_min_out_tttlb = cast5 Unmanaged._min_out_tttlb

_min_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_min_out_tttl = cast4 Unmanaged._min_out_tttl

mse_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_out_tttl = cast4 Unmanaged.mse_loss_out_tttl

mse_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
mse_loss_out_ttt = cast3 Unmanaged.mse_loss_out_ttt

mse_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_ttl = cast3 Unmanaged.mse_loss_ttl

mse_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
mse_loss_tt = cast2 Unmanaged.mse_loss_tt

mse_loss_backward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_backward_out_ttttl = cast5 Unmanaged.mse_loss_backward_out_ttttl

mse_loss_backward_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
mse_loss_backward_tttl = cast4 Unmanaged.mse_loss_backward_tttl

l1_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_out_tttl = cast4 Unmanaged.l1_loss_out_tttl

l1_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
l1_loss_out_ttt = cast3 Unmanaged.l1_loss_out_ttt

l1_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_ttl = cast3 Unmanaged.l1_loss_ttl

l1_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
l1_loss_tt = cast2 Unmanaged.l1_loss_tt

l1_loss_backward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_backward_out_ttttl = cast5 Unmanaged.l1_loss_backward_out_ttttl

l1_loss_backward_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
l1_loss_backward_tttl = cast4 Unmanaged.l1_loss_backward_tttl

multi_margin_loss_out_tttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttsstl = cast7 Unmanaged.multi_margin_loss_out_tttsstl

multi_margin_loss_out_tttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttsst = cast6 Unmanaged.multi_margin_loss_out_tttsst

multi_margin_loss_out_tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_tttss = cast5 Unmanaged.multi_margin_loss_out_tttss

multi_margin_loss_out_ttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_ttts = cast4 Unmanaged.multi_margin_loss_out_ttts

multi_margin_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_out_ttt = cast3 Unmanaged.multi_margin_loss_out_ttt

multi_margin_loss_ttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttsstl = cast6 Unmanaged.multi_margin_loss_ttsstl

multi_margin_loss_ttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttsst = cast5 Unmanaged.multi_margin_loss_ttsst

multi_margin_loss_ttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_ttss = cast4 Unmanaged.multi_margin_loss_ttss

multi_margin_loss_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_tts = cast3 Unmanaged.multi_margin_loss_tts

multi_margin_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_tt = cast2 Unmanaged.multi_margin_loss_tt

multi_margin_loss_backward_out_ttttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttsstl = cast8 Unmanaged.multi_margin_loss_backward_out_ttttsstl

multi_margin_loss_backward_out_ttttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttsst = cast7 Unmanaged.multi_margin_loss_backward_out_ttttsst

multi_margin_loss_backward_out_ttttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_out_ttttss = cast6 Unmanaged.multi_margin_loss_backward_out_ttttss

multi_margin_loss_backward_tttsstl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttsstl = cast7 Unmanaged.multi_margin_loss_backward_tttsstl

multi_margin_loss_backward_tttsst
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttsst = cast6 Unmanaged.multi_margin_loss_backward_tttsst

multi_margin_loss_backward_tttss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
multi_margin_loss_backward_tttss = cast5 Unmanaged.multi_margin_loss_backward_tttss

multilabel_margin_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_out_tttl = cast4 Unmanaged.multilabel_margin_loss_out_tttl

multilabel_margin_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_out_ttt = cast3 Unmanaged.multilabel_margin_loss_out_ttt

multilabel_margin_loss_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_ttl = cast3 Unmanaged.multilabel_margin_loss_ttl

multilabel_margin_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_tt = cast2 Unmanaged.multilabel_margin_loss_tt

multilabel_margin_loss_forward_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
multilabel_margin_loss_forward_out_ttttl = cast5 Unmanaged.multilabel_margin_loss_forward_out_ttttl

multilabel_margin_loss_forward_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
multilabel_margin_loss_forward_ttl = cast3 Unmanaged.multilabel_margin_loss_forward_ttl

multilabel_margin_loss_backward_out_ttttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_backward_out_ttttlt = cast6 Unmanaged.multilabel_margin_loss_backward_out_ttttlt

multilabel_margin_loss_backward_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
multilabel_margin_loss_backward_tttlt = cast5 Unmanaged.multilabel_margin_loss_backward_tttlt

nll_loss_out_ttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttttll = cast6 Unmanaged.nll_loss_out_ttttll

nll_loss_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttttl = cast5 Unmanaged.nll_loss_out_ttttl

nll_loss_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_out_tttt = cast4 Unmanaged.nll_loss_out_tttt

nll_loss_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_out_ttt = cast3 Unmanaged.nll_loss_out_ttt

nll_loss_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_tttll = cast5 Unmanaged.nll_loss_tttll

nll_loss_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss_tttl = cast4 Unmanaged.nll_loss_tttl

nll_loss_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_ttt = cast3 Unmanaged.nll_loss_ttt

nll_loss_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_tt = cast2 Unmanaged.nll_loss_tt

nll_loss_forward_out_tttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss_forward_out_tttttll = cast7 Unmanaged.nll_loss_forward_out_tttttll

nll_loss_forward_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss_forward_tttll = cast5 Unmanaged.nll_loss_forward_tttll

nll_loss_backward_out_tttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_backward_out_tttttllt = cast8 Unmanaged.nll_loss_backward_out_tttttllt

nll_loss_backward_ttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss_backward_ttttllt = cast7 Unmanaged.nll_loss_backward_ttttllt

nll_loss2d_out_ttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttttll = cast6 Unmanaged.nll_loss2d_out_ttttll

nll_loss2d_out_ttttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttttl = cast5 Unmanaged.nll_loss2d_out_ttttl

nll_loss2d_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_tttt = cast4 Unmanaged.nll_loss2d_out_tttt

nll_loss2d_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_out_ttt = cast3 Unmanaged.nll_loss2d_out_ttt

nll_loss2d_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_tttll = cast5 Unmanaged.nll_loss2d_tttll

nll_loss2d_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nll_loss2d_tttl = cast4 Unmanaged.nll_loss2d_tttl

nll_loss2d_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_ttt = cast3 Unmanaged.nll_loss2d_ttt

nll_loss2d_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_tt = cast2 Unmanaged.nll_loss2d_tt

nll_loss2d_forward_out_tttttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss2d_forward_out_tttttll = cast7 Unmanaged.nll_loss2d_forward_out_tttttll

nll_loss2d_forward_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
nll_loss2d_forward_tttll = cast5 Unmanaged.nll_loss2d_forward_tttll

nll_loss2d_backward_out_tttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_backward_out_tttttllt = cast8 Unmanaged.nll_loss2d_backward_out_tttttllt

nll_loss2d_backward_ttttllt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nll_loss2d_backward_ttttllt = cast7 Unmanaged.nll_loss2d_backward_ttttllt

smooth_l1_loss_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
smooth_l1_loss_out_tttl = cast4 Unmanaged.smooth_l1_loss_out_tttl
