
-- generated by using spec/Declarations.yaml

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module Torch.Internal.Managed.Native.Native10 where


import Foreign.C.String
import Foreign.C.Types
import Foreign
import Torch.Internal.Type
import Torch.Internal.Class
import Torch.Internal.Cast
import Torch.Internal.Objects
import qualified Torch.Internal.Unmanaged.Native.Native10 as Unmanaged


upsample_bicubic2d_backward_out_ttllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_bicubic2d_backward_out_ttllbdd = _cast7 Unmanaged.upsample_bicubic2d_backward_out_ttllbdd

upsample_bicubic2d_backward_out_ttllbd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_bicubic2d_backward_out_ttllbd = _cast6 Unmanaged.upsample_bicubic2d_backward_out_ttllbd

upsample_bicubic2d_backward_out_ttllb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_bicubic2d_backward_out_ttllb = _cast5 Unmanaged.upsample_bicubic2d_backward_out_ttllb

upsample_bicubic2d_backward_tllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_bicubic2d_backward_tllbdd = _cast6 Unmanaged.upsample_bicubic2d_backward_tllbdd

upsample_bicubic2d_backward_tllb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_bicubic2d_backward_tllb = _cast4 Unmanaged.upsample_bicubic2d_backward_tllb

_upsample_bicubic2d_aa_out_ttlbdd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_out_ttlbdd = _cast6 Unmanaged._upsample_bicubic2d_aa_out_ttlbdd

_upsample_bicubic2d_aa_out_ttlbd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_out_ttlbd = _cast5 Unmanaged._upsample_bicubic2d_aa_out_ttlbd

_upsample_bicubic2d_aa_out_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_out_ttlb = _cast4 Unmanaged._upsample_bicubic2d_aa_out_ttlb

_upsample_bicubic2d_aa_tlbdd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_tlbdd = _cast5 Unmanaged._upsample_bicubic2d_aa_tlbdd

-- _upsample_bicubic2d_aa_tlbd
--   :: ForeignPtr Tensor
--   -> ForeignPtr IntArray
--   -> CBool
--   -> CDouble
--   -> IO (ForeignPtr Tensor)
-- _upsample_bicubic2d_aa_tlbd = _cast4 Unmanaged._upsample_bicubic2d_aa_tlbd

_upsample_bicubic2d_aa_tlb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_tlb = _cast3 Unmanaged._upsample_bicubic2d_aa_tlb

_upsample_bicubic2d_aa_backward_out_ttllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_out_ttllbdd = _cast7 Unmanaged._upsample_bicubic2d_aa_backward_out_ttllbdd

_upsample_bicubic2d_aa_backward_out_ttllbd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_out_ttllbd = _cast6 Unmanaged._upsample_bicubic2d_aa_backward_out_ttllbd

_upsample_bicubic2d_aa_backward_out_ttllb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_out_ttllb = _cast5 Unmanaged._upsample_bicubic2d_aa_backward_out_ttllb

_upsample_bicubic2d_aa_backward_tllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_tllbdd = _cast6 Unmanaged._upsample_bicubic2d_aa_backward_tllbdd

_upsample_bicubic2d_aa_backward_tllbd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_tllbd = _cast5 Unmanaged._upsample_bicubic2d_aa_backward_tllbd

_upsample_bicubic2d_aa_backward_tllb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
_upsample_bicubic2d_aa_backward_tllb = _cast4 Unmanaged._upsample_bicubic2d_aa_backward_tllb

upsample_trilinear3d_out_ttlbddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_out_ttlbddd = _cast7 Unmanaged.upsample_trilinear3d_out_ttlbddd

upsample_trilinear3d_out_ttlbdd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_out_ttlbdd = _cast6 Unmanaged.upsample_trilinear3d_out_ttlbdd

upsample_trilinear3d_out_ttlbd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_out_ttlbd = _cast5 Unmanaged.upsample_trilinear3d_out_ttlbd

upsample_trilinear3d_out_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_out_ttlb = _cast4 Unmanaged.upsample_trilinear3d_out_ttlb

upsample_trilinear3d_tlbddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_tlbddd = _cast6 Unmanaged.upsample_trilinear3d_tlbddd

upsample_trilinear3d_tlbdd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_tlbdd = _cast5 Unmanaged.upsample_trilinear3d_tlbdd

upsample_trilinear3d_tlb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_tlb = _cast3 Unmanaged.upsample_trilinear3d_tlb

upsample_trilinear3d_backward_out_ttllbddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_out_ttllbddd = _cast8 Unmanaged.upsample_trilinear3d_backward_out_ttllbddd

upsample_trilinear3d_backward_out_ttllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_out_ttllbdd = _cast7 Unmanaged.upsample_trilinear3d_backward_out_ttllbdd

upsample_trilinear3d_backward_out_ttllbd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_out_ttllbd = _cast6 Unmanaged.upsample_trilinear3d_backward_out_ttllbd

upsample_trilinear3d_backward_out_ttllb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_out_ttllb = _cast5 Unmanaged.upsample_trilinear3d_backward_out_ttllb

upsample_trilinear3d_backward_tllbddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_tllbddd = _cast7 Unmanaged.upsample_trilinear3d_backward_tllbddd

upsample_trilinear3d_backward_tllbdd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_tllbdd = _cast6 Unmanaged.upsample_trilinear3d_backward_tllbdd

upsample_trilinear3d_backward_tllb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
upsample_trilinear3d_backward_tllb = _cast4 Unmanaged.upsample_trilinear3d_backward_tllb

upsample_nearest1d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_out_ttld = _cast4 Unmanaged.upsample_nearest1d_out_ttld

upsample_nearest1d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_out_ttl = _cast3 Unmanaged.upsample_nearest1d_out_ttl

_upsample_nearest_exact1d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_out_ttld = _cast4 Unmanaged._upsample_nearest_exact1d_out_ttld

_upsample_nearest_exact1d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_out_ttl = _cast3 Unmanaged._upsample_nearest_exact1d_out_ttl

upsample_nearest1d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_tl = _cast2 Unmanaged.upsample_nearest1d_tl

-- _upsample_nearest_exact1d_tld
--   :: ForeignPtr Tensor
--   -> ForeignPtr IntArray
--   -> CDouble
--   -> IO (ForeignPtr Tensor)
-- _upsample_nearest_exact1d_tld = _cast3 Unmanaged._upsample_nearest_exact1d_tld

_upsample_nearest_exact1d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_tl = _cast2 Unmanaged._upsample_nearest_exact1d_tl

upsample_nearest1d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_backward_out_ttlld = _cast5 Unmanaged.upsample_nearest1d_backward_out_ttlld

upsample_nearest1d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_backward_out_ttll = _cast4 Unmanaged.upsample_nearest1d_backward_out_ttll

_upsample_nearest_exact1d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_backward_out_ttlld = _cast5 Unmanaged._upsample_nearest_exact1d_backward_out_ttlld

_upsample_nearest_exact1d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_backward_out_ttll = _cast4 Unmanaged._upsample_nearest_exact1d_backward_out_ttll

upsample_nearest1d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest1d_backward_tll = _cast3 Unmanaged.upsample_nearest1d_backward_tll

_upsample_nearest_exact1d_backward_tlld
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_backward_tlld = _cast4 Unmanaged._upsample_nearest_exact1d_backward_tlld

_upsample_nearest_exact1d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact1d_backward_tll = _cast3 Unmanaged._upsample_nearest_exact1d_backward_tll

upsample_nearest2d_out_ttldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_out_ttldd = _cast5 Unmanaged.upsample_nearest2d_out_ttldd

upsample_nearest2d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_out_ttld = _cast4 Unmanaged.upsample_nearest2d_out_ttld

upsample_nearest2d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_out_ttl = _cast3 Unmanaged.upsample_nearest2d_out_ttl

_upsample_nearest_exact2d_out_ttldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_out_ttldd = _cast5 Unmanaged._upsample_nearest_exact2d_out_ttldd

_upsample_nearest_exact2d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_out_ttld = _cast4 Unmanaged._upsample_nearest_exact2d_out_ttld

_upsample_nearest_exact2d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_out_ttl = _cast3 Unmanaged._upsample_nearest_exact2d_out_ttl

upsample_nearest2d_tldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_tldd = _cast4 Unmanaged.upsample_nearest2d_tldd

upsample_nearest2d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_tl = _cast2 Unmanaged.upsample_nearest2d_tl

_upsample_nearest_exact2d_tldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_tldd = _cast4 Unmanaged._upsample_nearest_exact2d_tldd

-- _upsample_nearest_exact2d_tld
--   :: ForeignPtr Tensor
--   -> ForeignPtr IntArray
--   -> CDouble
--   -> IO (ForeignPtr Tensor)
-- _upsample_nearest_exact2d_tld = _cast3 Unmanaged._upsample_nearest_exact2d_tld

_upsample_nearest_exact2d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_tl = _cast2 Unmanaged._upsample_nearest_exact2d_tl

upsample_nearest2d_backward_out_ttlldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_backward_out_ttlldd = _cast6 Unmanaged.upsample_nearest2d_backward_out_ttlldd

upsample_nearest2d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_backward_out_ttlld = _cast5 Unmanaged.upsample_nearest2d_backward_out_ttlld

upsample_nearest2d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_backward_out_ttll = _cast4 Unmanaged.upsample_nearest2d_backward_out_ttll

_upsample_nearest_exact2d_backward_out_ttlldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_out_ttlldd = _cast6 Unmanaged._upsample_nearest_exact2d_backward_out_ttlldd

_upsample_nearest_exact2d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_out_ttlld = _cast5 Unmanaged._upsample_nearest_exact2d_backward_out_ttlld

_upsample_nearest_exact2d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_out_ttll = _cast4 Unmanaged._upsample_nearest_exact2d_backward_out_ttll

upsample_nearest2d_backward_tlldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_backward_tlldd = _cast5 Unmanaged.upsample_nearest2d_backward_tlldd

upsample_nearest2d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest2d_backward_tll = _cast3 Unmanaged.upsample_nearest2d_backward_tll

_upsample_nearest_exact2d_backward_tlldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_tlldd = _cast5 Unmanaged._upsample_nearest_exact2d_backward_tlldd

_upsample_nearest_exact2d_backward_tlld
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_tlld = _cast4 Unmanaged._upsample_nearest_exact2d_backward_tlld

_upsample_nearest_exact2d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact2d_backward_tll = _cast3 Unmanaged._upsample_nearest_exact2d_backward_tll

upsample_nearest3d_out_ttlddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_out_ttlddd = _cast6 Unmanaged.upsample_nearest3d_out_ttlddd

upsample_nearest3d_out_ttldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_out_ttldd = _cast5 Unmanaged.upsample_nearest3d_out_ttldd

upsample_nearest3d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_out_ttld = _cast4 Unmanaged.upsample_nearest3d_out_ttld

upsample_nearest3d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_out_ttl = _cast3 Unmanaged.upsample_nearest3d_out_ttl

_upsample_nearest_exact3d_out_ttlddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_out_ttlddd = _cast6 Unmanaged._upsample_nearest_exact3d_out_ttlddd

_upsample_nearest_exact3d_out_ttldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_out_ttldd = _cast5 Unmanaged._upsample_nearest_exact3d_out_ttldd

_upsample_nearest_exact3d_out_ttld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_out_ttld = _cast4 Unmanaged._upsample_nearest_exact3d_out_ttld

_upsample_nearest_exact3d_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_out_ttl = _cast3 Unmanaged._upsample_nearest_exact3d_out_ttl

upsample_nearest3d_tlddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_tlddd = _cast5 Unmanaged.upsample_nearest3d_tlddd

upsample_nearest3d_tldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_tldd = _cast4 Unmanaged.upsample_nearest3d_tldd

upsample_nearest3d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_tl = _cast2 Unmanaged.upsample_nearest3d_tl

_upsample_nearest_exact3d_tlddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_tlddd = _cast5 Unmanaged._upsample_nearest_exact3d_tlddd

_upsample_nearest_exact3d_tldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_tldd = _cast4 Unmanaged._upsample_nearest_exact3d_tldd

-- _upsample_nearest_exact3d_tld
--   :: ForeignPtr Tensor
--   -> ForeignPtr IntArray
--   -> CDouble
--   -> IO (ForeignPtr Tensor)
-- _upsample_nearest_exact3d_tld = _cast3 Unmanaged._upsample_nearest_exact3d_tld

_upsample_nearest_exact3d_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_tl = _cast2 Unmanaged._upsample_nearest_exact3d_tl

upsample_nearest3d_backward_out_ttllddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_out_ttllddd = _cast7 Unmanaged.upsample_nearest3d_backward_out_ttllddd

upsample_nearest3d_backward_out_ttlldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_out_ttlldd = _cast6 Unmanaged.upsample_nearest3d_backward_out_ttlldd

upsample_nearest3d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_out_ttlld = _cast5 Unmanaged.upsample_nearest3d_backward_out_ttlld

upsample_nearest3d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_out_ttll = _cast4 Unmanaged.upsample_nearest3d_backward_out_ttll

_upsample_nearest_exact3d_backward_out_ttllddd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_out_ttllddd = _cast7 Unmanaged._upsample_nearest_exact3d_backward_out_ttllddd

_upsample_nearest_exact3d_backward_out_ttlldd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_out_ttlldd = _cast6 Unmanaged._upsample_nearest_exact3d_backward_out_ttlldd

_upsample_nearest_exact3d_backward_out_ttlld
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_out_ttlld = _cast5 Unmanaged._upsample_nearest_exact3d_backward_out_ttlld

_upsample_nearest_exact3d_backward_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_out_ttll = _cast4 Unmanaged._upsample_nearest_exact3d_backward_out_ttll

upsample_nearest3d_backward_tllddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_tllddd = _cast6 Unmanaged.upsample_nearest3d_backward_tllddd

upsample_nearest3d_backward_tlldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_tlldd = _cast5 Unmanaged.upsample_nearest3d_backward_tlldd

upsample_nearest3d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
upsample_nearest3d_backward_tll = _cast3 Unmanaged.upsample_nearest3d_backward_tll

_upsample_nearest_exact3d_backward_tllddd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_tllddd = _cast6 Unmanaged._upsample_nearest_exact3d_backward_tllddd

_upsample_nearest_exact3d_backward_tlldd
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_tlldd = _cast5 Unmanaged._upsample_nearest_exact3d_backward_tlldd

_upsample_nearest_exact3d_backward_tlld
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> CDouble
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_tlld = _cast4 Unmanaged._upsample_nearest_exact3d_backward_tlld

_upsample_nearest_exact3d_backward_tll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_upsample_nearest_exact3d_backward_tll = _cast3 Unmanaged._upsample_nearest_exact3d_backward_tll

sigmoid_backward_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
sigmoid_backward_out_ttt = _cast3 Unmanaged.sigmoid_backward_out_ttt

sigmoid_backward_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
sigmoid_backward_tt = _cast2 Unmanaged.sigmoid_backward_tt

logit_backward_out_tttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
logit_backward_out_tttd = _cast4 Unmanaged.logit_backward_out_tttd

logit_backward_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
logit_backward_out_ttt = _cast3 Unmanaged.logit_backward_out_ttt

logit_backward_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
logit_backward_ttd = _cast3 Unmanaged.logit_backward_ttd

logit_backward_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
logit_backward_tt = _cast2 Unmanaged.logit_backward_tt

tanh_backward_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
tanh_backward_out_ttt = _cast3 Unmanaged.tanh_backward_out_ttt

tanh_backward_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
tanh_backward_tt = _cast2 Unmanaged.tanh_backward_tt

slow_conv_transpose2d_out_tttltllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttltllll = _cast9 Unmanaged.slow_conv_transpose2d_out_tttltllll

slow_conv_transpose2d_out_tttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttltlll = _cast8 Unmanaged.slow_conv_transpose2d_out_tttltlll

slow_conv_transpose2d_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttltll = _cast7 Unmanaged.slow_conv_transpose2d_out_tttltll

slow_conv_transpose2d_out_tttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttltl = _cast6 Unmanaged.slow_conv_transpose2d_out_tttltl

slow_conv_transpose2d_out_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttlt = _cast5 Unmanaged.slow_conv_transpose2d_out_tttlt

slow_conv_transpose2d_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_out_tttl = _cast4 Unmanaged.slow_conv_transpose2d_out_tttl

slow_conv_transpose2d_ttltllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttltllll = _cast8 Unmanaged.slow_conv_transpose2d_ttltllll

slow_conv_transpose2d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttltlll = _cast7 Unmanaged.slow_conv_transpose2d_ttltlll

slow_conv_transpose2d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttltll = _cast6 Unmanaged.slow_conv_transpose2d_ttltll

slow_conv_transpose2d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttltl = _cast5 Unmanaged.slow_conv_transpose2d_ttltl

slow_conv_transpose2d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttlt = _cast4 Unmanaged.slow_conv_transpose2d_ttlt

slow_conv_transpose2d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose2d_ttl = _cast3 Unmanaged.slow_conv_transpose2d_ttl

slow_conv_transpose3d_out_tttltllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttltllll = _cast9 Unmanaged.slow_conv_transpose3d_out_tttltllll

slow_conv_transpose3d_out_tttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttltlll = _cast8 Unmanaged.slow_conv_transpose3d_out_tttltlll

slow_conv_transpose3d_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttltll = _cast7 Unmanaged.slow_conv_transpose3d_out_tttltll

slow_conv_transpose3d_out_tttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttltl = _cast6 Unmanaged.slow_conv_transpose3d_out_tttltl

slow_conv_transpose3d_out_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttlt = _cast5 Unmanaged.slow_conv_transpose3d_out_tttlt

slow_conv_transpose3d_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_out_tttl = _cast4 Unmanaged.slow_conv_transpose3d_out_tttl

slow_conv_transpose3d_ttltllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttltllll = _cast8 Unmanaged.slow_conv_transpose3d_ttltllll

slow_conv_transpose3d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttltlll = _cast7 Unmanaged.slow_conv_transpose3d_ttltlll

slow_conv_transpose3d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttltll = _cast6 Unmanaged.slow_conv_transpose3d_ttltll

slow_conv_transpose3d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttltl = _cast5 Unmanaged.slow_conv_transpose3d_ttltl

slow_conv_transpose3d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttlt = _cast4 Unmanaged.slow_conv_transpose3d_ttlt

slow_conv_transpose3d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_transpose3d_ttl = _cast3 Unmanaged.slow_conv_transpose3d_ttl

thnn_conv2d_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_out_tttltll = _cast7 Unmanaged.thnn_conv2d_out_tttltll

thnn_conv2d_out_tttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_out_tttltl = _cast6 Unmanaged.thnn_conv2d_out_tttltl

thnn_conv2d_out_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
thnn_conv2d_out_tttlt = _cast5 Unmanaged.thnn_conv2d_out_tttlt

thnn_conv2d_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_out_tttl = _cast4 Unmanaged.thnn_conv2d_out_tttl

thnn_conv2d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_ttltll = _cast6 Unmanaged.thnn_conv2d_ttltll

thnn_conv2d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_ttltl = _cast5 Unmanaged.thnn_conv2d_ttltl

thnn_conv2d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
thnn_conv2d_ttlt = _cast4 Unmanaged.thnn_conv2d_ttlt

thnn_conv2d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
thnn_conv2d_ttl = _cast3 Unmanaged.thnn_conv2d_ttl

_slow_conv2d_forward_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_slow_conv2d_forward_out_tttltll = _cast7 Unmanaged._slow_conv2d_forward_out_tttltll

_slow_conv2d_forward_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_slow_conv2d_forward_ttltll = _cast6 Unmanaged._slow_conv2d_forward_ttltll

_slow_conv2d_backward_out_ttttttlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor,Tensor)))
_slow_conv2d_backward_out_ttttttlll = _cast9 Unmanaged._slow_conv2d_backward_out_ttttttlll

_slow_conv2d_backward_tttllla
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr (StdArray '(CBool,3))
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor,Tensor)))
_slow_conv2d_backward_tttllla = _cast7 Unmanaged._slow_conv2d_backward_tttllla

_conv_depthwise2d_out_tttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_conv_depthwise2d_out_tttltlll = _cast8 Unmanaged._conv_depthwise2d_out_tttltlll

_conv_depthwise2d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
_conv_depthwise2d_ttltlll = _cast7 Unmanaged._conv_depthwise2d_ttltlll

conv_depthwise3d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
conv_depthwise3d_ttltlll = _cast7 Unmanaged.conv_depthwise3d_ttltlll

slow_conv3d_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_out_tttltll = _cast7 Unmanaged.slow_conv3d_out_tttltll

slow_conv3d_out_tttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_out_tttltl = _cast6 Unmanaged.slow_conv3d_out_tttltl

slow_conv3d_out_tttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv3d_out_tttlt = _cast5 Unmanaged.slow_conv3d_out_tttlt

slow_conv3d_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_out_tttl = _cast4 Unmanaged.slow_conv3d_out_tttl

slow_conv3d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_ttltll = _cast6 Unmanaged.slow_conv3d_ttltll

slow_conv3d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_ttltl = _cast5 Unmanaged.slow_conv3d_ttltl

slow_conv3d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv3d_ttlt = _cast4 Unmanaged.slow_conv3d_ttlt

slow_conv3d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_ttl = _cast3 Unmanaged.slow_conv3d_ttl

slow_conv3d_forward_out_tttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_forward_out_tttltll = _cast7 Unmanaged.slow_conv3d_forward_out_tttltll

slow_conv3d_forward_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv3d_forward_ttltll = _cast6 Unmanaged.slow_conv3d_forward_ttltll

slow_conv_dilated2d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated2d_ttltlll = _cast7 Unmanaged.slow_conv_dilated2d_ttltlll

slow_conv_dilated2d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated2d_ttltll = _cast6 Unmanaged.slow_conv_dilated2d_ttltll

slow_conv_dilated2d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated2d_ttltl = _cast5 Unmanaged.slow_conv_dilated2d_ttltl

slow_conv_dilated2d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_dilated2d_ttlt = _cast4 Unmanaged.slow_conv_dilated2d_ttlt

slow_conv_dilated2d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated2d_ttl = _cast3 Unmanaged.slow_conv_dilated2d_ttl

slow_conv_dilated3d_ttltlll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated3d_ttltlll = _cast7 Unmanaged.slow_conv_dilated3d_ttltlll

slow_conv_dilated3d_ttltll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated3d_ttltll = _cast6 Unmanaged.slow_conv_dilated3d_ttltll

slow_conv_dilated3d_ttltl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated3d_ttltl = _cast5 Unmanaged.slow_conv_dilated3d_ttltl

slow_conv_dilated3d_ttlt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
slow_conv_dilated3d_ttlt = _cast4 Unmanaged.slow_conv_dilated3d_ttlt

slow_conv_dilated3d_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
slow_conv_dilated3d_ttl = _cast3 Unmanaged.slow_conv_dilated3d_ttl

col2im_out_ttlllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
col2im_out_ttlllll = _cast7 Unmanaged.col2im_out_ttlllll

col2im_tlllll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
col2im_tlllll = _cast6 Unmanaged.col2im_tlllll

column_stack_l
  :: ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
column_stack_l = _cast1 Unmanaged.column_stack_l

column_stack_out_tl
  :: ForeignPtr Tensor
  -> ForeignPtr TensorList
  -> IO (ForeignPtr Tensor)
column_stack_out_tl = _cast2 Unmanaged.column_stack_out_tl

im2col_out_ttllll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
im2col_out_ttllll = _cast6 Unmanaged.im2col_out_ttllll

im2col_tllll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
im2col_tllll = _cast5 Unmanaged.im2col_tllll

isfinite_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isfinite_t = _cast1 Unmanaged.isfinite_t

isinf_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isinf_t = _cast1 Unmanaged.isinf_t

isposinf_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isposinf_t = _cast1 Unmanaged.isposinf_t

isposinf_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isposinf_out_tt = _cast2 Unmanaged.isposinf_out_tt

isneginf_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isneginf_t = _cast1 Unmanaged.isneginf_t

isneginf_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
isneginf_out_tt = _cast2 Unmanaged.isneginf_out_tt

_add_batch_dim_tll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
_add_batch_dim_tll = _cast3 Unmanaged._add_batch_dim_tll

_remove_batch_dim_tlll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
_remove_batch_dim_tlll = _cast4 Unmanaged._remove_batch_dim_tlll

special_entr_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_entr_t = _cast1 Unmanaged.special_entr_t

special_entr_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_entr_out_tt = _cast2 Unmanaged.special_entr_out_tt

special_ndtri_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_ndtri_t = _cast1 Unmanaged.special_ndtri_t

special_ndtri_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_ndtri_out_tt = _cast2 Unmanaged.special_ndtri_out_tt

special_log_ndtr_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_log_ndtr_t = _cast1 Unmanaged.special_log_ndtr_t

special_log_ndtr_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_log_ndtr_out_tt = _cast2 Unmanaged.special_log_ndtr_out_tt

special_expm1_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_expm1_t = _cast1 Unmanaged.special_expm1_t

special_expm1_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_expm1_out_tt = _cast2 Unmanaged.special_expm1_out_tt

special_exp2_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_exp2_t = _cast1 Unmanaged.special_exp2_t

special_exp2_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_exp2_out_tt = _cast2 Unmanaged.special_exp2_out_tt

special_psi_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_psi_t = _cast1 Unmanaged.special_psi_t

special_psi_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_psi_out_tt = _cast2 Unmanaged.special_psi_out_tt

special_digamma_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_digamma_t = _cast1 Unmanaged.special_digamma_t

special_digamma_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_digamma_out_tt = _cast2 Unmanaged.special_digamma_out_tt

special_gammaln_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammaln_t = _cast1 Unmanaged.special_gammaln_t

special_gammaln_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammaln_out_tt = _cast2 Unmanaged.special_gammaln_out_tt

special_erf_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erf_t = _cast1 Unmanaged.special_erf_t

special_erf_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erf_out_tt = _cast2 Unmanaged.special_erf_out_tt

special_erfc_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfc_t = _cast1 Unmanaged.special_erfc_t

special_erfc_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfc_out_tt = _cast2 Unmanaged.special_erfc_out_tt

special_erfcx_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfcx_t = _cast1 Unmanaged.special_erfcx_t

special_erfcx_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfcx_out_tt = _cast2 Unmanaged.special_erfcx_out_tt

special_erfinv_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfinv_t = _cast1 Unmanaged.special_erfinv_t

special_erfinv_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_erfinv_out_tt = _cast2 Unmanaged.special_erfinv_out_tt

special_ndtr_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_ndtr_t = _cast1 Unmanaged.special_ndtr_t

special_ndtr_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_ndtr_out_tt = _cast2 Unmanaged.special_ndtr_out_tt

special_xlog1py_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlog1py_tt = _cast2 Unmanaged.special_xlog1py_tt

special_xlog1py_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlog1py_st = _cast2 Unmanaged.special_xlog1py_st

special_xlog1py_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_xlog1py_ts = _cast2 Unmanaged.special_xlog1py_ts

special_xlog1py_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlog1py_out_ttt = _cast3 Unmanaged.special_xlog1py_out_ttt

special_xlog1py_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlog1py_out_tst = _cast3 Unmanaged.special_xlog1py_out_tst

special_xlog1py_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_xlog1py_out_tts = _cast3 Unmanaged.special_xlog1py_out_tts

special_xlogy_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlogy_tt = _cast2 Unmanaged.special_xlogy_tt

special_xlogy_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlogy_st = _cast2 Unmanaged.special_xlogy_st

special_xlogy_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_xlogy_ts = _cast2 Unmanaged.special_xlogy_ts

special_xlogy_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlogy_out_ttt = _cast3 Unmanaged.special_xlogy_out_ttt

special_xlogy_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_xlogy_out_tst = _cast3 Unmanaged.special_xlogy_out_tst

special_xlogy_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_xlogy_out_tts = _cast3 Unmanaged.special_xlogy_out_tts

special_zeta_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_zeta_tt = _cast2 Unmanaged.special_zeta_tt

special_zeta_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_zeta_st = _cast2 Unmanaged.special_zeta_st

special_zeta_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_zeta_ts = _cast2 Unmanaged.special_zeta_ts

special_zeta_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_zeta_out_ttt = _cast3 Unmanaged.special_zeta_out_ttt

special_zeta_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_zeta_out_tst = _cast3 Unmanaged.special_zeta_out_tst

special_zeta_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
special_zeta_out_tts = _cast3 Unmanaged.special_zeta_out_tts

special_i0_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i0_t = _cast1 Unmanaged.special_i0_t

special_i0_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i0_out_tt = _cast2 Unmanaged.special_i0_out_tt

special_i0e_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i0e_t = _cast1 Unmanaged.special_i0e_t

special_i0e_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i0e_out_tt = _cast2 Unmanaged.special_i0e_out_tt

special_i1_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i1_t = _cast1 Unmanaged.special_i1_t

special_i1_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i1_out_tt = _cast2 Unmanaged.special_i1_out_tt

special_i1e_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i1e_t = _cast1 Unmanaged.special_i1e_t

special_i1e_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_i1e_out_tt = _cast2 Unmanaged.special_i1e_out_tt

special_logit_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
special_logit_td = _cast2 Unmanaged.special_logit_td

special_logit_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_logit_t = _cast1 Unmanaged.special_logit_t

special_logit_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
special_logit_out_ttd = _cast3 Unmanaged.special_logit_out_ttd

special_logit_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_logit_out_tt = _cast2 Unmanaged.special_logit_out_tt

special_polygamma_lt
  :: Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_polygamma_lt = _cast2 Unmanaged.special_polygamma_lt

special_polygamma_out_tlt
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_polygamma_out_tlt = _cast3 Unmanaged.special_polygamma_out_tlt

special_logsumexp_tlb
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
special_logsumexp_tlb = _cast3 Unmanaged.special_logsumexp_tlb

special_logsumexp_tl
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
special_logsumexp_tl = _cast2 Unmanaged.special_logsumexp_tl

special_logsumexp_out_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> CBool
  -> IO (ForeignPtr Tensor)
special_logsumexp_out_ttlb = _cast4 Unmanaged.special_logsumexp_out_ttlb

special_logsumexp_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
special_logsumexp_out_ttl = _cast3 Unmanaged.special_logsumexp_out_ttl

special_expit_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_expit_t = _cast1 Unmanaged.special_expit_t

special_expit_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_expit_out_tt = _cast2 Unmanaged.special_expit_out_tt

special_sinc_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_sinc_t = _cast1 Unmanaged.special_sinc_t

special_sinc_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_sinc_out_tt = _cast2 Unmanaged.special_sinc_out_tt

special_round_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_round_tl = _cast2 Unmanaged.special_round_tl

special_round_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_round_t = _cast1 Unmanaged.special_round_t

special_round_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_round_out_ttl = _cast3 Unmanaged.special_round_out_ttl

special_round_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_round_out_tt = _cast2 Unmanaged.special_round_out_tt

special_log1p_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_log1p_t = _cast1 Unmanaged.special_log1p_t

special_log1p_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_log1p_out_tt = _cast2 Unmanaged.special_log1p_out_tt

special_log_softmax_tls
  :: ForeignPtr Tensor
  -> Int64
  -> ScalarType
  -> IO (ForeignPtr Tensor)
special_log_softmax_tls = _cast3 Unmanaged.special_log_softmax_tls

special_log_softmax_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_log_softmax_tl = _cast2 Unmanaged.special_log_softmax_tl

special_gammainc_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammainc_out_ttt = _cast3 Unmanaged.special_gammainc_out_ttt

special_gammainc_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammainc_tt = _cast2 Unmanaged.special_gammainc_tt

special_gammaincc_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammaincc_out_ttt = _cast3 Unmanaged.special_gammaincc_out_ttt

special_gammaincc_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
special_gammaincc_tt = _cast2 Unmanaged.special_gammaincc_tt

special_multigammaln_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_multigammaln_tl = _cast2 Unmanaged.special_multigammaln_tl

special_multigammaln_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_multigammaln_out_ttl = _cast3 Unmanaged.special_multigammaln_out_ttl

special_softmax_tls
  :: ForeignPtr Tensor
  -> Int64
  -> ScalarType
  -> IO (ForeignPtr Tensor)
special_softmax_tls = _cast3 Unmanaged.special_softmax_tls

special_softmax_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
special_softmax_tl = _cast2 Unmanaged.special_softmax_tl

fft_fft_tlls
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_fft_tlls = _cast4 Unmanaged.fft_fft_tlls

fft_fft_tll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_fft_tll = _cast3 Unmanaged.fft_fft_tll

fft_fft_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_fft_tl = _cast2 Unmanaged.fft_fft_tl

fft_fft_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fft_fft_t = _cast1 Unmanaged.fft_fft_t

fft_fft_out_ttlls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_fft_out_ttlls = _cast5 Unmanaged.fft_fft_out_ttlls

fft_fft_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_fft_out_ttll = _cast4 Unmanaged.fft_fft_out_ttll

fft_fft_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_fft_out_ttl = _cast3 Unmanaged.fft_fft_out_ttl

fft_fft_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fft_fft_out_tt = _cast2 Unmanaged.fft_fft_out_tt

fft_ifft_tlls
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_ifft_tlls = _cast4 Unmanaged.fft_ifft_tlls

fft_ifft_tll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_ifft_tll = _cast3 Unmanaged.fft_ifft_tll

fft_ifft_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_ifft_tl = _cast2 Unmanaged.fft_ifft_tl

fft_ifft_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fft_ifft_t = _cast1 Unmanaged.fft_ifft_t

fft_ifft_out_ttlls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_ifft_out_ttlls = _cast5 Unmanaged.fft_ifft_out_ttlls

fft_ifft_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_ifft_out_ttll = _cast4 Unmanaged.fft_ifft_out_ttll

fft_ifft_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_ifft_out_ttl = _cast3 Unmanaged.fft_ifft_out_ttl

fft_ifft_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fft_ifft_out_tt = _cast2 Unmanaged.fft_ifft_out_tt

fft_rfft_tlls
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_rfft_tlls = _cast4 Unmanaged.fft_rfft_tlls

fft_rfft_tll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_rfft_tll = _cast3 Unmanaged.fft_rfft_tll

fft_rfft_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_rfft_tl = _cast2 Unmanaged.fft_rfft_tl

fft_rfft_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fft_rfft_t = _cast1 Unmanaged.fft_rfft_t

fft_rfft_out_ttlls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> ForeignPtr StdString
  -> IO (ForeignPtr Tensor)
fft_rfft_out_ttlls = _cast5 Unmanaged.fft_rfft_out_ttlls

fft_rfft_out_ttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_rfft_out_ttll = _cast4 Unmanaged.fft_rfft_out_ttll

fft_rfft_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
fft_rfft_out_ttl = _cast3 Unmanaged.fft_rfft_out_ttl

