
-- generated by using spec/Declarations.yaml

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

module Torch.Internal.Managed.Native.Native11 where


import Foreign.C.String
import Foreign.C.Types
import Foreign
import Torch.Internal.Type
import Torch.Internal.Class
import Torch.Internal.Cast
import Torch.Internal.Objects
import qualified Torch.Internal.Unmanaged.Native.Native11 as Unmanaged


ormqr_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
ormqr_out_tttt = cast4 Unmanaged.ormqr_out_tttt

ormqr_tttbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr Tensor)
ormqr_tttbb = cast5 Unmanaged.ormqr_tttbb

ormqr_tttb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr Tensor)
ormqr_tttb = cast4 Unmanaged.ormqr_tttb

ormqr_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
ormqr_ttt = cast3 Unmanaged.ormqr_ttt

_lu_with_info_tbb
  :: ForeignPtr Tensor
  -> CBool
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor,Tensor)))
_lu_with_info_tbb = cast3 Unmanaged._lu_with_info_tbb

_lu_with_info_tb
  :: ForeignPtr Tensor
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor,Tensor)))
_lu_with_info_tb = cast2 Unmanaged._lu_with_info_tb

_lu_with_info_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor,Tensor)))
_lu_with_info_t = cast1 Unmanaged._lu_with_info_t

lu_solve_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lu_solve_out_tttt = cast4 Unmanaged.lu_solve_out_tttt

lu_solve_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lu_solve_ttt = cast3 Unmanaged.lu_solve_ttt

_lu_solve_helper_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_lu_solve_helper_ttt = cast3 Unmanaged._lu_solve_helper_ttt

multinomial_out_ttlbG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
multinomial_out_ttlbG = cast5 Unmanaged.multinomial_out_ttlbG

multinomial_out_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
multinomial_out_ttlb = cast4 Unmanaged.multinomial_out_ttlb

multinomial_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multinomial_out_ttl = cast3 Unmanaged.multinomial_out_ttl

multinomial_tlbG
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
multinomial_tlbG = cast4 Unmanaged.multinomial_tlbG

multinomial_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
multinomial_tlb = cast3 Unmanaged.multinomial_tlb

multinomial_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
multinomial_tl = cast2 Unmanaged.multinomial_tl

_multinomial_alias_setup_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
_multinomial_alias_setup_t = cast1 Unmanaged._multinomial_alias_setup_t

_multinomial_alias_draw_ttlG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
_multinomial_alias_draw_ttlG = cast4 Unmanaged._multinomial_alias_draw_ttlG

_multinomial_alias_draw_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
_multinomial_alias_draw_ttl = cast3 Unmanaged._multinomial_alias_draw_ttl

lgamma_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lgamma_out_tt = cast2 Unmanaged.lgamma_out_tt

lgamma_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lgamma_t = cast1 Unmanaged.lgamma_t

digamma_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
digamma_out_tt = cast2 Unmanaged.digamma_out_tt

digamma_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
digamma_t = cast1 Unmanaged.digamma_t

polygamma_out_tlt
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
polygamma_out_tlt = cast3 Unmanaged.polygamma_out_tlt

polygamma_lt
  :: Int64
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
polygamma_lt = cast2 Unmanaged.polygamma_lt

erfinv_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
erfinv_t = cast1 Unmanaged.erfinv_t

erfinv_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
erfinv_out_tt = cast2 Unmanaged.erfinv_out_tt

i0_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
i0_t = cast1 Unmanaged.i0_t

i0__t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
i0__t = cast1 Unmanaged.i0__t

i0_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
i0_out_tt = cast2 Unmanaged.i0_out_tt

sign_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
sign_t = cast1 Unmanaged.sign_t

sign_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
sign_out_tt = cast2 Unmanaged.sign_out_tt

signbit_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
signbit_t = cast1 Unmanaged.signbit_t

signbit_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
signbit_out_tt = cast2 Unmanaged.signbit_out_tt

dist_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
dist_tts = cast3 Unmanaged.dist_tts

dist_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
dist_tt = cast2 Unmanaged.dist_tt

atan2_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
atan2_out_ttt = cast3 Unmanaged.atan2_out_ttt

atan2_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
atan2_tt = cast2 Unmanaged.atan2_tt

lerp_out_ttts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
lerp_out_ttts = cast4 Unmanaged.lerp_out_ttts

lerp_out_tttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lerp_out_tttt = cast4 Unmanaged.lerp_out_tttt

lerp_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
lerp_tts = cast3 Unmanaged.lerp_tts

lerp_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
lerp_ttt = cast3 Unmanaged.lerp_ttt

histc_out_ttlss
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
histc_out_ttlss = cast5 Unmanaged.histc_out_ttlss

histc_out_ttls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
histc_out_ttls = cast4 Unmanaged.histc_out_ttls

histc_out_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
histc_out_ttl = cast3 Unmanaged.histc_out_ttl

histc_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
histc_out_tt = cast2 Unmanaged.histc_out_tt

histc_tlss
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Scalar
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
histc_tlss = cast4 Unmanaged.histc_tlss

histc_tls
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
histc_tls = cast3 Unmanaged.histc_tls

histc_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
histc_tl = cast2 Unmanaged.histc_tl

histc_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
histc_t = cast1 Unmanaged.histc_t

fmod_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
fmod_out_tts = cast3 Unmanaged.fmod_out_tts

fmod_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
fmod_ts = cast2 Unmanaged.fmod_ts

fmod_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fmod_out_ttt = cast3 Unmanaged.fmod_out_ttt

fmod_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
fmod_tt = cast2 Unmanaged.fmod_tt

hypot_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
hypot_out_ttt = cast3 Unmanaged.hypot_out_ttt

hypot_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
hypot_tt = cast2 Unmanaged.hypot_tt

nextafter_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nextafter_out_ttt = cast3 Unmanaged.nextafter_out_ttt

nextafter_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nextafter_tt = cast2 Unmanaged.nextafter_tt

remainder_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
remainder_out_tts = cast3 Unmanaged.remainder_out_tts

remainder_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
remainder_ts = cast2 Unmanaged.remainder_ts

remainder_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
remainder_out_ttt = cast3 Unmanaged.remainder_out_ttt

remainder_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
remainder_tt = cast2 Unmanaged.remainder_tt

min_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
min_t = cast1 Unmanaged.min_t

max_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
max_t = cast1 Unmanaged.max_t

maximum_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
maximum_tt = cast2 Unmanaged.maximum_tt

maximum_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
maximum_out_ttt = cast3 Unmanaged.maximum_out_ttt

max_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
max_tt = cast2 Unmanaged.max_tt

max_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
max_out_ttt = cast3 Unmanaged.max_out_ttt

minimum_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
minimum_tt = cast2 Unmanaged.minimum_tt

minimum_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
minimum_out_ttt = cast3 Unmanaged.minimum_out_ttt

min_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
min_out_ttt = cast3 Unmanaged.min_out_ttt

min_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
min_tt = cast2 Unmanaged.min_tt

median_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
median_t = cast1 Unmanaged.median_t

quantile_out_ttdlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
quantile_out_ttdlb = cast5 Unmanaged.quantile_out_ttdlb

quantile_out_ttdl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
quantile_out_ttdl = cast4 Unmanaged.quantile_out_ttdl

quantile_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
quantile_out_ttd = cast3 Unmanaged.quantile_out_ttd

quantile_tdlb
  :: ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
quantile_tdlb = cast4 Unmanaged.quantile_tdlb

quantile_tdl
  :: ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
quantile_tdl = cast3 Unmanaged.quantile_tdl

quantile_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
quantile_td = cast2 Unmanaged.quantile_td

quantile_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
quantile_out_tttlb = cast5 Unmanaged.quantile_out_tttlb

quantile_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
quantile_out_tttl = cast4 Unmanaged.quantile_out_tttl

quantile_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
quantile_out_ttt = cast3 Unmanaged.quantile_out_ttt

quantile_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
quantile_ttlb = cast4 Unmanaged.quantile_ttlb

quantile_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
quantile_ttl = cast3 Unmanaged.quantile_ttl

quantile_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
quantile_tt = cast2 Unmanaged.quantile_tt

nanquantile_out_ttdlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
nanquantile_out_ttdlb = cast5 Unmanaged.nanquantile_out_ttdlb

nanquantile_out_ttdl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
nanquantile_out_ttdl = cast4 Unmanaged.nanquantile_out_ttdl

nanquantile_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
nanquantile_out_ttd = cast3 Unmanaged.nanquantile_out_ttd

nanquantile_tdlb
  :: ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
nanquantile_tdlb = cast4 Unmanaged.nanquantile_tdlb

nanquantile_tdl
  :: ForeignPtr Tensor
  -> CDouble
  -> Int64
  -> IO (ForeignPtr Tensor)
nanquantile_tdl = cast3 Unmanaged.nanquantile_tdl

nanquantile_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
nanquantile_td = cast2 Unmanaged.nanquantile_td

nanquantile_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
nanquantile_out_tttlb = cast5 Unmanaged.nanquantile_out_tttlb

nanquantile_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nanquantile_out_tttl = cast4 Unmanaged.nanquantile_out_tttl

nanquantile_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nanquantile_out_ttt = cast3 Unmanaged.nanquantile_out_ttt

nanquantile_ttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
nanquantile_ttlb = cast4 Unmanaged.nanquantile_ttlb

nanquantile_ttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
nanquantile_ttl = cast3 Unmanaged.nanquantile_ttl

nanquantile_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
nanquantile_tt = cast2 Unmanaged.nanquantile_tt

sort_out_tttlb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_out_tttlb = cast5 Unmanaged.sort_out_tttlb

sort_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_out_tttl = cast4 Unmanaged.sort_out_tttl

sort_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_out_ttt = cast3 Unmanaged.sort_out_ttt

sort_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_tlb = cast3 Unmanaged.sort_tlb

sort_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_tl = cast2 Unmanaged.sort_tl

sort_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_t = cast1 Unmanaged.sort_t

sort_out_tttnb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_out_tttnb = cast5 Unmanaged.sort_out_tttnb

sort_out_tttn
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_out_tttn = cast4 Unmanaged.sort_out_tttn

sort_tnb
  :: ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_tnb = cast3 Unmanaged.sort_tnb

sort_tn
  :: ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
sort_tn = cast2 Unmanaged.sort_tn

argsort_tlb
  :: ForeignPtr Tensor
  -> Int64
  -> CBool
  -> IO (ForeignPtr Tensor)
argsort_tlb = cast3 Unmanaged.argsort_tlb

argsort_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr Tensor)
argsort_tl = cast2 Unmanaged.argsort_tl

argsort_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
argsort_t = cast1 Unmanaged.argsort_t

argsort_tnb
  :: ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> CBool
  -> IO (ForeignPtr Tensor)
argsort_tnb = cast3 Unmanaged.argsort_tnb

argsort_tn
  :: ForeignPtr Tensor
  -> ForeignPtr Dimname
  -> IO (ForeignPtr Tensor)
argsort_tn = cast2 Unmanaged.argsort_tn

topk_out_tttllbb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> CBool
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_out_tttllbb = cast7 Unmanaged.topk_out_tttllbb

topk_out_tttllb
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_out_tttllb = cast6 Unmanaged.topk_out_tttllb

topk_out_tttll
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_out_tttll = cast5 Unmanaged.topk_out_tttll

topk_out_tttl
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_out_tttl = cast4 Unmanaged.topk_out_tttl

topk_tllbb
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> CBool
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_tllbb = cast5 Unmanaged.topk_tllbb

topk_tllb
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> CBool
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_tllb = cast4 Unmanaged.topk_tllb

topk_tll
  :: ForeignPtr Tensor
  -> Int64
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_tll = cast3 Unmanaged.topk_tll

topk_tl
  :: ForeignPtr Tensor
  -> Int64
  -> IO (ForeignPtr (StdTuple '(Tensor,Tensor)))
topk_tl = cast2 Unmanaged.topk_tl

all_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
all_t = cast1 Unmanaged.all_t

any_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
any_t = cast1 Unmanaged.any_t

renorm_out_ttsls
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
renorm_out_ttsls = cast5 Unmanaged.renorm_out_ttsls

renorm_tsls
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> Int64
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
renorm_tsls = cast4 Unmanaged.renorm_tsls

unfold_backward_tllll
  :: ForeignPtr Tensor
  -> ForeignPtr IntArray
  -> Int64
  -> Int64
  -> Int64
  -> IO (ForeignPtr Tensor)
unfold_backward_tllll = cast5 Unmanaged.unfold_backward_tllll

equal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (CBool)
equal_tt = cast2 Unmanaged.equal_tt

pow_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_ttt = cast3 Unmanaged.pow_out_ttt

pow_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_tt = cast2 Unmanaged.pow_tt

pow_out_tst
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_out_tst = cast3 Unmanaged.pow_out_tst

pow_st
  :: ForeignPtr Scalar
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
pow_st = cast2 Unmanaged.pow_st

pow_out_tts
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
pow_out_tts = cast3 Unmanaged.pow_out_tts

pow_ts
  :: ForeignPtr Tensor
  -> ForeignPtr Scalar
  -> IO (ForeignPtr Tensor)
pow_ts = cast2 Unmanaged.pow_ts

normal_out_ttdG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_ttdG = cast4 Unmanaged.normal_out_ttdG

normal_out_ttd
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_out_ttd = cast3 Unmanaged.normal_out_ttd

normal_out_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tt = cast2 Unmanaged.normal_out_tt

normal_tdG
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_tdG = cast3 Unmanaged.normal_tdG

normal_td
  :: ForeignPtr Tensor
  -> CDouble
  -> IO (ForeignPtr Tensor)
normal_td = cast2 Unmanaged.normal_td

normal_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_t = cast1 Unmanaged.normal_t

normal_out_tdtG
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tdtG = cast4 Unmanaged.normal_out_tdtG

normal_out_tdt
  :: ForeignPtr Tensor
  -> CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_tdt = cast3 Unmanaged.normal_out_tdt

normal_dtG
  :: CDouble
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_dtG = cast3 Unmanaged.normal_dtG

normal_dt
  :: CDouble
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_dt = cast2 Unmanaged.normal_dt

normal_out_tttG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tttG = cast4 Unmanaged.normal_out_tttG

normal_out_ttt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_out_ttt = cast3 Unmanaged.normal_out_ttt

normal_ttG
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ttG = cast3 Unmanaged.normal_ttG

normal_tt
  :: ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
normal_tt = cast2 Unmanaged.normal_tt

normal_ddlGo
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> ForeignPtr TensorOptions
  -> IO (ForeignPtr Tensor)
normal_ddlGo = cast5 Unmanaged.normal_ddlGo

normal_ddlG
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_ddlG = cast4 Unmanaged.normal_ddlG

normal_ddl
  :: CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_ddl = cast3 Unmanaged.normal_ddl

normal_out_tddlG
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> ForeignPtr Generator
  -> IO (ForeignPtr Tensor)
normal_out_tddlG = cast5 Unmanaged.normal_out_tddlG

normal_out_tddl
  :: ForeignPtr Tensor
  -> CDouble
  -> CDouble
  -> ForeignPtr IntArray
  -> IO (ForeignPtr Tensor)
normal_out_tddl = cast4 Unmanaged.normal_out_tddl

alias_t
  :: ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
alias_t = cast1 Unmanaged.alias_t

_index_copy__tltt
  :: ForeignPtr Tensor
  -> Int64
  -> ForeignPtr Tensor
  -> ForeignPtr Tensor
  -> IO (ForeignPtr Tensor)
_index_copy__tltt = cast4 Unmanaged._index_copy__tltt

