name: nix-linux-cu10

on:
  push:
    branches:
      - master

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: free disk space
  #       run: |
  #         sudo swapoff -a
  #         sudo rm -f /swapfile
  #         sudo apt -y purge ghc* cabal-install* php* || true
  #         sudo apt autoremove -y || true
  #         sudo apt autoclean -y || true
  #         docker rmi $(docker image ls -aq)
  #         df -h
  #     - uses: cachix/install-nix-action@v10
  #     - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
  #     - run: cachix use hasktorch
  #     - run: cachix use iohk
  #     - run: |
  #         nix-build -j 2 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.libtorch-ffi.checks.spec
  #         nix-build -j 2 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.hasktorch.checks.spec
  #         nix-build -j 2 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.examples.checks.spec
  build-cache:
    if: github.repository == 'hasktorch/hasktorch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt -y purge ghc* cabal-install* php* || true
          sudo apt autoremove -y || true
          sudo apt autoclean -y || true
          docker rmi $(docker image ls -aq)
          df -h
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: |
          nix-build -j 2 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.libtorch-ffi.checks.spec
          nix-build -j 1 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.hasktorch.checks.spec
          nix-build -j 1 --arg cudaSupport true --argstr cudaMajorVersion 10 -A haskellPackages.examples.checks.spec
