name: stack-ghc810-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -y purge ghc* cabal-install* php* || true
        sudo apt autoremove -y || true
        sudo apt autoclean -y || true
        docker rmi $(docker image ls -aq)
        df -h
    - name: Setup packages
      run: |
        sudo apt update -qq
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install cmake curl wget unzip git libtinfo-dev python3 python3-yaml
        (wget -qO- https://get.haskellstack.org/ | sh) || true
    - name: Setup repos
      run: |
        git submodule init && git submodule update
    - name: Build
      run: |
        export PATH=/opt/ghc/bin:$PATH
        source setenv
        pushd deps/ ; ./get-deps.sh -a cpu -c; popd
        stack build --stack-yaml stack-ghc810.yaml
    - name: Test
      run: |
        export PATH=/opt/ghc/bin:$PATH
        source setenv
        stack test codegen --stack-yaml stack-ghc810.yaml
        stack test libtorch-ffi --stack-yaml stack-ghc810.yaml
        stack test hasktorch --stack-yaml stack-ghc810.yaml
        stack exec codegen-exe --stack-yaml stack-ghc810.yaml
        stack exec xor-mlp --stack-yaml stack-ghc810.yaml
