module Torch.Class.Tensor.Math where

import THTypes
import Foreign
import Foreign.C.Types
import Torch.Class.Internal

class TensorMath t where
  fill         :: t -> HsReal t -> IO ()
  zero         :: t -> IO ()
  maskedFill   :: t -> Ptr CTHByteTensor -> HsReal t -> IO ()
  maskedCopy   :: t -> Ptr CTHByteTensor -> t -> IO ()
  maskedSelect :: t -> t -> Ptr CTHByteTensor -> IO ()
  nonzero      :: Ptr CTHLongTensor -> t -> IO ()
  indexSelect  :: t -> t -> CInt -> Ptr CTHLongTensor -> IO ()
  indexCopy    :: t -> CInt -> Ptr CTHLongTensor -> t -> IO ()
  indexAdd     :: t -> CInt -> Ptr CTHLongTensor -> t -> IO ()
  indexFill    :: t -> CInt -> Ptr CTHLongTensor -> HsReal t > IO ()
  take         :: t -> t -> Ptr CTHLongTensor -> IO ()
  put          :: t -> Ptr CTHLongTensor -> t -> CInt -> IO ()
  gather       :: t -> t -> CInt -> Ptr CTHLongTensor -> IO ()
  scatter      :: t -> CInt -> Ptr CTHLongTensor -> t -> IO ()
  scatterAdd   :: t -> CInt -> Ptr CTHLongTensor -> t -> IO ()
  scatterFill  :: t -> CInt -> Ptr CTHLongTensor -> HsReal t > IO ()
  dot          :: t -> t -> HsAccReal t
  minall       :: t -> HsReal t
  maxall       :: t -> HsReal t
  medianall    :: t -> HsReal t
  sumall       :: t -> HsAccReal t
  prodall      :: t -> HsAccReal t
  add          :: t -> t -> HsReal t > IO ()
  sub          :: t -> t -> HsReal t > IO ()
  add_scaled   :: t -> t -> HsReal t > HsReal t > IO ()
  sub_scaled   :: t -> t -> HsReal t > HsReal t > IO ()
  mul          :: t -> t -> HsReal t > IO ()
  div          :: t -> t -> HsReal t > IO ()
  lshift       :: t -> t -> HsReal t > IO ()
  rshift       :: t -> t -> HsReal t > IO ()
  fmod         :: t -> t -> HsReal t > IO ()
  remainder    :: t -> t -> HsReal t > IO ()
  clamp        :: t -> t -> HsReal t > HsReal t > IO ()
  bitand       :: t -> t -> HsReal t > IO ()
  bitor        :: t -> t -> HsReal t > IO ()
  bitxor       :: t -> t -> HsReal t > IO ()
  cadd         :: t -> t -> HsReal t > t -> IO ()
  csub         :: t -> t -> HsReal t > t -> IO ()
  cmul         :: t -> t -> t -> IO ()
  cpow         :: t -> t -> t -> IO ()
  cdiv         :: t -> t -> t -> IO ()
  clshift      :: t -> t -> t -> IO ()
  crshift      :: t -> t -> t -> IO ()
  cfmod        :: t -> t -> t -> IO ()
  cremainder   :: t -> t -> t -> IO ()
  cbitand      :: t -> t -> t -> IO ()
  cbitor       :: t -> t -> t -> IO ()
  cbitxor      :: t -> t -> t -> IO ()
  addcmul      :: t -> t -> HsReal t > t -> t -> IO ()
  addcdiv      :: t -> t -> HsReal t > t -> t -> IO ()
  addmv        :: t -> HsReal t > t -> HsReal t > t -> t -> IO ()
  addmm        :: t -> HsReal t > t -> HsReal t > t -> t -> IO ()
  addr         :: t -> HsReal t > t -> HsReal t > t -> t -> IO ()
  addbmm       :: t -> HsReal t > t -> HsReal t > t -> t -> IO ()
  baddbmm      :: t -> HsReal t > t -> HsReal t > t -> t -> IO ()
  match        :: t -> t -> t -> HsReal t > IO ()
  numel        :: t -> CPtrdiff
  max          :: t -> Ptr CTHLongTensor -> t -> CInt -> CInt -> IO ()
  min          :: t -> Ptr CTHLongTensor -> t -> CInt -> CInt -> IO ()
  kthvalue     :: t -> Ptr CTHLongTensor -> t -> CLLong -> CInt -> CInt -> IO ()
  mode         :: t -> Ptr CTHLongTensor -> t -> CInt -> CInt -> IO ()
  median       :: t -> Ptr CTHLongTensor -> t -> CInt -> CInt -> IO ()
  sum          :: t -> t -> CInt -> CInt -> IO ()
  prod         :: t -> t -> CInt -> CInt -> IO ()
  cumsum       :: t -> t -> CInt -> IO ()
  cumprod      :: t -> t -> CInt -> IO ()
  sign         :: t -> t -> IO ()
  trace        :: t -> HsAccReal t
  cross        :: t -> t -> t -> CInt -> IO ()
  cmax         :: t -> t -> t -> IO ()
  cmin         :: t -> t -> t -> IO ()
  cmaxValue    :: t -> t -> HsReal t > IO ()
  cminValue    :: t -> t -> HsReal t > IO ()
  zeros        :: t -> Ptr CTHLongStorage -> IO ()
  zerosLike    :: t -> t -> IO ()
  ones         :: t -> Ptr CTHLongStorage -> IO ()
  onesLike     :: t -> t -> IO ()
  diag         :: t -> t -> CInt -> IO ()
  eye          :: t -> CLLong -> CLLong -> IO ()
  arange       :: t -> HsAccReal t-> HsAccReal t-> HsAccReal t-> IO ()
  range        :: t -> HsAccReal t-> HsAccReal t-> HsAccReal t-> IO ()
  randperm     :: t -> Ptr CTHGenerator -> CLLong -> IO ()
  reshape      :: t -> t -> Ptr CTHLongStorage -> IO ()
  sort         :: t -> Ptr CTHLongTensor -> t -> CInt -> CInt -> IO ()
  topk         :: t -> Ptr CTHLongTensor -> t -> CLLong -> CInt -> CInt -> CInt -> IO ()
  tril         :: t -> t -> CLLong -> IO ()
  triu         :: t -> t -> CLLong -> IO ()
  cat          :: t -> t -> t -> CInt -> IO ()
  catArray     :: t -> Ptr (t) -> CInt -> CInt -> IO ()
  equal        :: t -> t -> CInt
  ltValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  leValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  gtValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  geValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  neValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  eqValue      :: Ptr CTHByteTensor -> t -> HsReal t > IO ()
  ltValueT     :: t -> t -> HsReal t > IO ()
  leValueT     :: t -> t -> HsReal t > IO ()
  gtValueT     :: t -> t -> HsReal t > IO ()
  geValueT     :: t -> t -> HsReal t > IO ()
  neValueT     :: t -> t -> HsReal t > IO ()
  eqValueT     :: t -> t -> HsReal t > IO ()
  ltTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  leTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  gtTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  geTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  neTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  eqTensor     :: Ptr CTHByteTensor -> t -> t -> IO ()
  ltTensorT    :: t -> t -> t -> IO ()
  leTensorT    :: t -> t -> t -> IO ()
  gtTensorT    :: t -> t -> t -> IO ()
  geTensorT    :: t -> t -> t -> IO ()
  neTensorT    :: t -> t -> t -> IO ()
  eqTensorT    :: t -> t -> t -> IO ()

class THTensorMath t => THTensorMathNegative t where
  neg          :: t -> t -> IO ()
  abs          :: t -> t -> IO ()

class THTensorMath t => THTensorMathFloating t where
  cinv         :: t -> t -> IO ()
  sigmoid      :: t -> t -> IO ()
  log          :: t -> t -> IO ()
  lgamma       :: t -> t -> IO ()
  log1p        :: t -> t -> IO ()
  exp          :: t -> t -> IO ()
  cos          :: t -> t -> IO ()
  acos         :: t -> t -> IO ()
  cosh         :: t -> t -> IO ()
  sin          :: t -> t -> IO ()
  asin         :: t -> t -> IO ()
  sinh         :: t -> t -> IO ()
  tan          :: t -> t -> IO ()
  atan         :: t -> t -> IO ()
  atan2        :: t -> t -> t -> IO ()
  tanh         :: t -> t -> IO ()
  erf          :: t -> t -> IO ()
  erfinv       :: t -> t -> IO ()
  pow          :: t -> t -> HsReal t > IO ()
  tpow         :: t -> HsReal t > t -> IO ()
  sqrt         :: t -> t -> IO ()
  rsqrt        :: t -> t -> IO ()
  ceil         :: t -> t -> IO ()
  floor        :: t -> t -> IO ()
  round        :: t -> t -> IO ()
  trunc        :: t -> t -> IO ()
  frac         :: t -> t -> IO ()
  lerp         :: t -> t -> t -> HsReal t > IO ()
  mean         :: t -> t -> CInt -> CInt -> IO ()
  std          :: t -> t -> CInt -> CInt -> CInt -> IO ()
  var          :: t -> t -> CInt -> CInt -> CInt -> IO ()
  norm         :: t -> t -> HsReal t > CInt -> CInt -> IO ()
  renorm       :: t -> t -> HsReal t > CInt -> HsReal t > IO ()
  dist         :: t -> t -> HsReal t > HsAccReal t
  histc        :: t -> t -> CLLong -> HsReal t > HsReal t > IO ()
  bhistc       :: t -> t -> CLLong -> HsReal t > HsReal t > IO ()
  meanall      :: t -> HsAccReal t
  varall       :: t -> CInt -> HsAccReal t
  stdall       :: t -> CInt -> HsAccReal t
  normall      :: t -> HsReal t > HsAccReal t
  linspace     :: t -> HsReal t > HsReal t > CLLong -> IO ()
  logspace     :: t -> HsReal t > HsReal t > CLLong -> IO ()
  rand         :: t -> Ptr CTHGenerator -> Ptr CTHLongStorage -> IO ()
  randn        :: t -> Ptr CTHGenerator -> Ptr CTHLongStorage -> IO ()

